syntax="proto3";

option go_package = "github.com/orca-telemetry/contract/go";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "vendor/validate.proto";
import "worker.proto";
import "core.proto";

// Core is the central orchestration service that:
// - Registers resources such as data functions, tasks and workflows
// - Manages the lifecycle of triggering workflows
// - Coordinates algorithm execution across distributed processors
// - Tracks DAG execution state and handles distributed failure modes
service Core {
  // Registers a data function available for calling
  rpc RegisterDataFunction(DataFunction) return (DataFunctionRegistrationStatus)

  // Registers a task
  rpc RegisterTask(Task) return (TaskRegistrationStatus)

  // Registers a workflow
  rpc RegisterWorkflow(Workflow) return (WorkflowRegistrationStatus)
  
  // Triggers a workflow
  rpc TriggerWorkflow(Trigger) return (TriggerStatus)

  // Register the completion result of the data function
  rpc RegisterDataFunctionResult(DataFunctionResult) return (DataFunctionResultStatus)

  // Registers the result of a task
  rpc RegisterTaskResult(TaskResult) return (TaskResultStatus)

  // Expose the internal state of the orchestration stack
  rpc ExposeState(ExposeSettings) returns (InternalState);

  // Query past results of tasks
  rpc QueryTaskResult(QueryParams) returns (stream PastReults);
}

// Worker defines the service that a worker must implement to start listening
// for execution requests.
// 
// Workers are language-agnostic services that:
// - Execute Data Functions
// - Execute workflow segments, and route them to tasks
//
// Core utilises the workers  to asynchronously schedule task executions (via
// workflow segments) as per the distributed DAG.
service Worker
  // Execute a data function call
  rpc ExecuteDataFunction(DataFunction) returns (DataFunctionStatus);

  // Execute a workflow segment (potentially all of it)
  rpc ExecuteWorkflowSegment(ExecuteWorkflowRequest) returns (ExecutionWorkflowResult);

  // Check the liveness of a worker via a simple heartbeat
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
}

