// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: core.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Core_RegisterWorker_FullMethodName             = "/Core/RegisterWorker"
	Core_GetNonce_FullMethodName                   = "/Core/GetNonce"
	Core_CheckNonce_FullMethodName                 = "/Core/CheckNonce"
	Core_RegisterWorkerSnapshot_FullMethodName     = "/Core/RegisterWorkerSnapshot"
	Core_RegisterServing_FullMethodName            = "/Core/RegisterServing"
	Core_TriggerWorkflow_FullMethodName            = "/Core/TriggerWorkflow"
	Core_RegisterDataFunctionResult_FullMethodName = "/Core/RegisterDataFunctionResult"
	Core_RegisterTaskResult_FullMethodName         = "/Core/RegisterTaskResult"
	Core_ExposeState_FullMethodName                = "/Core/ExposeState"
	Core_QueryTaskResult_FullMethodName            = "/Core/QueryTaskResult"
)

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Core is the central orchestration service that:
// - Registers resources such as data functions, tasks and workflows
// - Manages the lifecycle of triggering workflows
// - Coordinates algorithm execution across distributed processors
// - Tracks DAG execution state and handles distributed failure modes
type CoreClient interface {
	// Registers a worker with core
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	// Get a nonce from the server
	GetNonce(ctx context.Context, in *GetNonceRequest, opts ...grpc.CallOption) (*GetNonceResponse, error)
	// Check a nonce with the server
	CheckNonce(ctx context.Context, in *CheckNonceRequest, opts ...grpc.CallOption) (*CheckNonceResponse, error)
	// Registers all assets defined in the worker's codebase.
	// This operation is idempotent on the worker name and git commit hash.
	RegisterWorkerSnapshot(ctx context.Context, in *RegisterWorkerSnapshotRequest, opts ...grpc.CallOption) (*RegisterWorkerSnapshotResponse, error)
	// Notify existence
	RegisterServing(ctx context.Context, in *RegisterServingRequest, opts ...grpc.CallOption) (*RegisterServingResponse, error)
	// Triggers a workflow
	TriggerWorkflow(ctx context.Context, in *TriggerWorkflowRequest, opts ...grpc.CallOption) (*TriggerWorkflowResponse, error)
	// Register the completion result of the data function
	RegisterDataFunctionResult(ctx context.Context, in *RegisterDataFunctionCompletionRequest, opts ...grpc.CallOption) (*RegisterDataFunctionCompletionResponse, error)
	// Registers the result of a task
	RegisterTaskResult(ctx context.Context, in *RegisterTaskResultRequest, opts ...grpc.CallOption) (*RegisterTaskResultResponse, error)
	// Expose the internal state of the orchestration stack
	ExposeState(ctx context.Context, in *ExposeStateRequest, opts ...grpc.CallOption) (*ExposeStateResponse, error)
	// Query past results of tasks
	QueryTaskResult(ctx context.Context, in *QueryTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTaskResponse], error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, Core_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetNonce(ctx context.Context, in *GetNonceRequest, opts ...grpc.CallOption) (*GetNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNonceResponse)
	err := c.cc.Invoke(ctx, Core_GetNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CheckNonce(ctx context.Context, in *CheckNonceRequest, opts ...grpc.CallOption) (*CheckNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNonceResponse)
	err := c.cc.Invoke(ctx, Core_CheckNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterWorkerSnapshot(ctx context.Context, in *RegisterWorkerSnapshotRequest, opts ...grpc.CallOption) (*RegisterWorkerSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerSnapshotResponse)
	err := c.cc.Invoke(ctx, Core_RegisterWorkerSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterServing(ctx context.Context, in *RegisterServingRequest, opts ...grpc.CallOption) (*RegisterServingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServingResponse)
	err := c.cc.Invoke(ctx, Core_RegisterServing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) TriggerWorkflow(ctx context.Context, in *TriggerWorkflowRequest, opts ...grpc.CallOption) (*TriggerWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerWorkflowResponse)
	err := c.cc.Invoke(ctx, Core_TriggerWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterDataFunctionResult(ctx context.Context, in *RegisterDataFunctionCompletionRequest, opts ...grpc.CallOption) (*RegisterDataFunctionCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDataFunctionCompletionResponse)
	err := c.cc.Invoke(ctx, Core_RegisterDataFunctionResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterTaskResult(ctx context.Context, in *RegisterTaskResultRequest, opts ...grpc.CallOption) (*RegisterTaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTaskResultResponse)
	err := c.cc.Invoke(ctx, Core_RegisterTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ExposeState(ctx context.Context, in *ExposeStateRequest, opts ...grpc.CallOption) (*ExposeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExposeStateResponse)
	err := c.cc.Invoke(ctx, Core_ExposeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) QueryTaskResult(ctx context.Context, in *QueryTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryTaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Core_ServiceDesc.Streams[0], Core_QueryTaskResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryTaskRequest, QueryTaskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Core_QueryTaskResultClient = grpc.ServerStreamingClient[QueryTaskResponse]

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility.
//
// Core is the central orchestration service that:
// - Registers resources such as data functions, tasks and workflows
// - Manages the lifecycle of triggering workflows
// - Coordinates algorithm execution across distributed processors
// - Tracks DAG execution state and handles distributed failure modes
type CoreServer interface {
	// Registers a worker with core
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	// Get a nonce from the server
	GetNonce(context.Context, *GetNonceRequest) (*GetNonceResponse, error)
	// Check a nonce with the server
	CheckNonce(context.Context, *CheckNonceRequest) (*CheckNonceResponse, error)
	// Registers all assets defined in the worker's codebase.
	// This operation is idempotent on the worker name and git commit hash.
	RegisterWorkerSnapshot(context.Context, *RegisterWorkerSnapshotRequest) (*RegisterWorkerSnapshotResponse, error)
	// Notify existence
	RegisterServing(context.Context, *RegisterServingRequest) (*RegisterServingResponse, error)
	// Triggers a workflow
	TriggerWorkflow(context.Context, *TriggerWorkflowRequest) (*TriggerWorkflowResponse, error)
	// Register the completion result of the data function
	RegisterDataFunctionResult(context.Context, *RegisterDataFunctionCompletionRequest) (*RegisterDataFunctionCompletionResponse, error)
	// Registers the result of a task
	RegisterTaskResult(context.Context, *RegisterTaskResultRequest) (*RegisterTaskResultResponse, error)
	// Expose the internal state of the orchestration stack
	ExposeState(context.Context, *ExposeStateRequest) (*ExposeStateResponse, error)
	// Query past results of tasks
	QueryTaskResult(*QueryTaskRequest, grpc.ServerStreamingServer[QueryTaskResponse]) error
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServer struct{}

func (UnimplementedCoreServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedCoreServer) GetNonce(context.Context, *GetNonceRequest) (*GetNonceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNonce not implemented")
}
func (UnimplementedCoreServer) CheckNonce(context.Context, *CheckNonceRequest) (*CheckNonceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckNonce not implemented")
}
func (UnimplementedCoreServer) RegisterWorkerSnapshot(context.Context, *RegisterWorkerSnapshotRequest) (*RegisterWorkerSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorkerSnapshot not implemented")
}
func (UnimplementedCoreServer) RegisterServing(context.Context, *RegisterServingRequest) (*RegisterServingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterServing not implemented")
}
func (UnimplementedCoreServer) TriggerWorkflow(context.Context, *TriggerWorkflowRequest) (*TriggerWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerWorkflow not implemented")
}
func (UnimplementedCoreServer) RegisterDataFunctionResult(context.Context, *RegisterDataFunctionCompletionRequest) (*RegisterDataFunctionCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDataFunctionResult not implemented")
}
func (UnimplementedCoreServer) RegisterTaskResult(context.Context, *RegisterTaskResultRequest) (*RegisterTaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTaskResult not implemented")
}
func (UnimplementedCoreServer) ExposeState(context.Context, *ExposeStateRequest) (*ExposeStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExposeState not implemented")
}
func (UnimplementedCoreServer) QueryTaskResult(*QueryTaskRequest, grpc.ServerStreamingServer[QueryTaskResponse]) error {
	return status.Error(codes.Unimplemented, "method QueryTaskResult not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}
func (UnimplementedCoreServer) testEmbeddedByValue()              {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	// If the following call panics, it indicates UnimplementedCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetNonce(ctx, req.(*GetNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CheckNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CheckNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CheckNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CheckNonce(ctx, req.(*CheckNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterWorkerSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterWorkerSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterWorkerSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterWorkerSnapshot(ctx, req.(*RegisterWorkerSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterServing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterServing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterServing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterServing(ctx, req.(*RegisterServingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_TriggerWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).TriggerWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_TriggerWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).TriggerWorkflow(ctx, req.(*TriggerWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterDataFunctionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDataFunctionCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterDataFunctionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterDataFunctionResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterDataFunctionResult(ctx, req.(*RegisterDataFunctionCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterTaskResult(ctx, req.(*RegisterTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ExposeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ExposeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ExposeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ExposeState(ctx, req.(*ExposeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_QueryTaskResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).QueryTaskResult(m, &grpc.GenericServerStream[QueryTaskRequest, QueryTaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Core_QueryTaskResultServer = grpc.ServerStreamingServer[QueryTaskResponse]

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _Core_RegisterWorker_Handler,
		},
		{
			MethodName: "GetNonce",
			Handler:    _Core_GetNonce_Handler,
		},
		{
			MethodName: "CheckNonce",
			Handler:    _Core_CheckNonce_Handler,
		},
		{
			MethodName: "RegisterWorkerSnapshot",
			Handler:    _Core_RegisterWorkerSnapshot_Handler,
		},
		{
			MethodName: "RegisterServing",
			Handler:    _Core_RegisterServing_Handler,
		},
		{
			MethodName: "TriggerWorkflow",
			Handler:    _Core_TriggerWorkflow_Handler,
		},
		{
			MethodName: "RegisterDataFunctionResult",
			Handler:    _Core_RegisterDataFunctionResult_Handler,
		},
		{
			MethodName: "RegisterTaskResult",
			Handler:    _Core_RegisterTaskResult_Handler,
		},
		{
			MethodName: "ExposeState",
			Handler:    _Core_ExposeState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryTaskResult",
			Handler:       _Core_QueryTaskResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
