// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: core.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Core_RegisterDataFunction_FullMethodName       = "/Core/RegisterDataFunction"
	Core_RegisterTask_FullMethodName               = "/Core/RegisterTask"
	Core_RegisterWorkflow_FullMethodName           = "/Core/RegisterWorkflow"
	Core_TriggerWorkflow_FullMethodName            = "/Core/TriggerWorkflow"
	Core_RegisterDataFunctionResult_FullMethodName = "/Core/RegisterDataFunctionResult"
	Core_RegisterTaskResult_FullMethodName         = "/Core/RegisterTaskResult"
	Core_ExposeState_FullMethodName                = "/Core/ExposeState"
	Core_QueryTaskResult_FullMethodName            = "/Core/QueryTaskResult"
)

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Core is the central orchestration service that:
// - Registers resources such as data functions, tasks and workflows
// - Manages the lifecycle of triggering workflows
// - Coordinates algorithm execution across distributed processors
// - Tracks DAG execution state and handles distributed failure modes
type CoreClient interface {
	// Registers a data function available for calling
	RegisterDataFunction(ctx context.Context, in *RegisterDataFunctionRequest, opts ...grpc.CallOption) (*RegisterDataFunctionResponse, error)
	// Registers a task
	RegisterTask(ctx context.Context, in *RegisterTaskRequest, opts ...grpc.CallOption) (*RegisterTaskResponse, error)
	// Registers a workflow
	RegisterWorkflow(ctx context.Context, in *RegisterWorkflowRequest, opts ...grpc.CallOption) (*RegisterWorkflowResponse, error)
	// Triggers a workflow
	TriggerWorkflow(ctx context.Context, in *TriggerWorkflowRequest, opts ...grpc.CallOption) (*TriggerWorkflowResponse, error)
	// Register the completion result of the data function
	RegisterDataFunctionResult(ctx context.Context, in *RegisterDataFunctionCompletionRequest, opts ...grpc.CallOption) (*RegisterDataFunctionCompletionResponse, error)
	// Registers the result of a task
	RegisterTaskResult(ctx context.Context, in *RegisterTaskResultRequest, opts ...grpc.CallOption) (*RegisterTaskResultResponse, error)
	// Expose the internal state of the orchestration stack
	ExposeState(ctx context.Context, in *ExposeStateRequest, opts ...grpc.CallOption) (*ExposeStateResponse, error)
	// Query past results of tasks
	QueryTaskResult(ctx context.Context, in *QueryParams, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PastResults], error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) RegisterDataFunction(ctx context.Context, in *RegisterDataFunctionRequest, opts ...grpc.CallOption) (*RegisterDataFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDataFunctionResponse)
	err := c.cc.Invoke(ctx, Core_RegisterDataFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterTask(ctx context.Context, in *RegisterTaskRequest, opts ...grpc.CallOption) (*RegisterTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTaskResponse)
	err := c.cc.Invoke(ctx, Core_RegisterTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterWorkflow(ctx context.Context, in *RegisterWorkflowRequest, opts ...grpc.CallOption) (*RegisterWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkflowResponse)
	err := c.cc.Invoke(ctx, Core_RegisterWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) TriggerWorkflow(ctx context.Context, in *TriggerWorkflowRequest, opts ...grpc.CallOption) (*TriggerWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerWorkflowResponse)
	err := c.cc.Invoke(ctx, Core_TriggerWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterDataFunctionResult(ctx context.Context, in *RegisterDataFunctionCompletionRequest, opts ...grpc.CallOption) (*RegisterDataFunctionCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDataFunctionCompletionResponse)
	err := c.cc.Invoke(ctx, Core_RegisterDataFunctionResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) RegisterTaskResult(ctx context.Context, in *RegisterTaskResultRequest, opts ...grpc.CallOption) (*RegisterTaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTaskResultResponse)
	err := c.cc.Invoke(ctx, Core_RegisterTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ExposeState(ctx context.Context, in *ExposeStateRequest, opts ...grpc.CallOption) (*ExposeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExposeStateResponse)
	err := c.cc.Invoke(ctx, Core_ExposeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) QueryTaskResult(ctx context.Context, in *QueryParams, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PastResults], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Core_ServiceDesc.Streams[0], Core_QueryTaskResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryParams, PastResults]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Core_QueryTaskResultClient = grpc.ServerStreamingClient[PastResults]

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility.
//
// Core is the central orchestration service that:
// - Registers resources such as data functions, tasks and workflows
// - Manages the lifecycle of triggering workflows
// - Coordinates algorithm execution across distributed processors
// - Tracks DAG execution state and handles distributed failure modes
type CoreServer interface {
	// Registers a data function available for calling
	RegisterDataFunction(context.Context, *RegisterDataFunctionRequest) (*RegisterDataFunctionResponse, error)
	// Registers a task
	RegisterTask(context.Context, *RegisterTaskRequest) (*RegisterTaskResponse, error)
	// Registers a workflow
	RegisterWorkflow(context.Context, *RegisterWorkflowRequest) (*RegisterWorkflowResponse, error)
	// Triggers a workflow
	TriggerWorkflow(context.Context, *TriggerWorkflowRequest) (*TriggerWorkflowResponse, error)
	// Register the completion result of the data function
	RegisterDataFunctionResult(context.Context, *RegisterDataFunctionCompletionRequest) (*RegisterDataFunctionCompletionResponse, error)
	// Registers the result of a task
	RegisterTaskResult(context.Context, *RegisterTaskResultRequest) (*RegisterTaskResultResponse, error)
	// Expose the internal state of the orchestration stack
	ExposeState(context.Context, *ExposeStateRequest) (*ExposeStateResponse, error)
	// Query past results of tasks
	QueryTaskResult(*QueryParams, grpc.ServerStreamingServer[PastResults]) error
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServer struct{}

func (UnimplementedCoreServer) RegisterDataFunction(context.Context, *RegisterDataFunctionRequest) (*RegisterDataFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDataFunction not implemented")
}
func (UnimplementedCoreServer) RegisterTask(context.Context, *RegisterTaskRequest) (*RegisterTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTask not implemented")
}
func (UnimplementedCoreServer) RegisterWorkflow(context.Context, *RegisterWorkflowRequest) (*RegisterWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorkflow not implemented")
}
func (UnimplementedCoreServer) TriggerWorkflow(context.Context, *TriggerWorkflowRequest) (*TriggerWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerWorkflow not implemented")
}
func (UnimplementedCoreServer) RegisterDataFunctionResult(context.Context, *RegisterDataFunctionCompletionRequest) (*RegisterDataFunctionCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDataFunctionResult not implemented")
}
func (UnimplementedCoreServer) RegisterTaskResult(context.Context, *RegisterTaskResultRequest) (*RegisterTaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTaskResult not implemented")
}
func (UnimplementedCoreServer) ExposeState(context.Context, *ExposeStateRequest) (*ExposeStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExposeState not implemented")
}
func (UnimplementedCoreServer) QueryTaskResult(*QueryParams, grpc.ServerStreamingServer[PastResults]) error {
	return status.Error(codes.Unimplemented, "method QueryTaskResult not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}
func (UnimplementedCoreServer) testEmbeddedByValue()              {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	// If the following call panics, it indicates UnimplementedCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_RegisterDataFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDataFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterDataFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterDataFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterDataFunction(ctx, req.(*RegisterDataFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterTask(ctx, req.(*RegisterTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterWorkflow(ctx, req.(*RegisterWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_TriggerWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).TriggerWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_TriggerWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).TriggerWorkflow(ctx, req.(*TriggerWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterDataFunctionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDataFunctionCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterDataFunctionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterDataFunctionResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterDataFunctionResult(ctx, req.(*RegisterDataFunctionCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_RegisterTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).RegisterTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_RegisterTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).RegisterTaskResult(ctx, req.(*RegisterTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ExposeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ExposeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ExposeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ExposeState(ctx, req.(*ExposeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_QueryTaskResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).QueryTaskResult(m, &grpc.GenericServerStream[QueryParams, PastResults]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Core_QueryTaskResultServer = grpc.ServerStreamingServer[PastResults]

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDataFunction",
			Handler:    _Core_RegisterDataFunction_Handler,
		},
		{
			MethodName: "RegisterTask",
			Handler:    _Core_RegisterTask_Handler,
		},
		{
			MethodName: "RegisterWorkflow",
			Handler:    _Core_RegisterWorkflow_Handler,
		},
		{
			MethodName: "TriggerWorkflow",
			Handler:    _Core_TriggerWorkflow_Handler,
		},
		{
			MethodName: "RegisterDataFunctionResult",
			Handler:    _Core_RegisterDataFunctionResult_Handler,
		},
		{
			MethodName: "RegisterTaskResult",
			Handler:    _Core_RegisterTaskResult_Handler,
		},
		{
			MethodName: "ExposeState",
			Handler:    _Core_ExposeState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryTaskResult",
			Handler:       _Core_QueryTaskResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
