// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: core.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The comparator to apply in a LeafFilter.
type Comparator int32

const (
	Comparator_COMPARATOR_UNSPECIFIED Comparator = 0
	Comparator_EQ                     Comparator = 1  // Equal to
	Comparator_NEQ                    Comparator = 2  // Not equal to
	Comparator_GT                     Comparator = 3  // Greater than
	Comparator_GTE                    Comparator = 4  // Greater than or equal to
	Comparator_LT                     Comparator = 5  // Less than
	Comparator_LTE                    Comparator = 6  // Less than or equal to
	Comparator_IN                     Comparator = 7  // Value is one of a set
	Comparator_NOT_IN                 Comparator = 8  // Value is not any of a set
	Comparator_EXISTS                 Comparator = 9  // Key is present (no value required)
	Comparator_NOT_EXISTS             Comparator = 10 // Key is absent (no value required)
	Comparator_CONTAINS               Comparator = 11 // Value contains the given substring
	Comparator_PREFIX                 Comparator = 12 // Value starts with the given string
)

// Enum value maps for Comparator.
var (
	Comparator_name = map[int32]string{
		0:  "COMPARATOR_UNSPECIFIED",
		1:  "EQ",
		2:  "NEQ",
		3:  "GT",
		4:  "GTE",
		5:  "LT",
		6:  "LTE",
		7:  "IN",
		8:  "NOT_IN",
		9:  "EXISTS",
		10: "NOT_EXISTS",
		11: "CONTAINS",
		12: "PREFIX",
	}
	Comparator_value = map[string]int32{
		"COMPARATOR_UNSPECIFIED": 0,
		"EQ":                     1,
		"NEQ":                    2,
		"GT":                     3,
		"GTE":                    4,
		"LT":                     5,
		"LTE":                    6,
		"IN":                     7,
		"NOT_IN":                 8,
		"EXISTS":                 9,
		"NOT_EXISTS":             10,
		"CONTAINS":               11,
		"PREFIX":                 12,
	}
)

func (x Comparator) Enum() *Comparator {
	p := new(Comparator)
	*p = x
	return p
}

func (x Comparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Comparator) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[0].Descriptor()
}

func (Comparator) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[0]
}

func (x Comparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Comparator.Descriptor instead.
func (Comparator) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

// Identifies which data source a key belongs to, used in OrderByStatement.
type DataSource int32

const (
	DataSource_DATA_SOURCE_UNSPECIFIED DataSource = 0
	DataSource_RESULT                  DataSource = 1
	DataSource_EXECUTION_PARAMETERS    DataSource = 2
)

// Enum value maps for DataSource.
var (
	DataSource_name = map[int32]string{
		0: "DATA_SOURCE_UNSPECIFIED",
		1: "RESULT",
		2: "EXECUTION_PARAMETERS",
	}
	DataSource_value = map[string]int32{
		"DATA_SOURCE_UNSPECIFIED": 0,
		"RESULT":                  1,
		"EXECUTION_PARAMETERS":    2,
	}
)

func (x DataSource) Enum() *DataSource {
	p := new(DataSource)
	*p = x
	return p
}

func (x DataSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataSource) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[1].Descriptor()
}

func (DataSource) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[1]
}

func (x DataSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataSource.Descriptor instead.
func (DataSource) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

// Sort direction for an OrderByStatement.
type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_ASC                        SortDirection = 1
	SortDirection_DESC                       SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "ASC",
		2: "DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"ASC":                        1,
		"DESC":                       2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[2].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[2]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

// DataFunction defines a registered data function and its metadata.
type DataFunction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the globally unique identifier for this data function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Hash is the hash of the AST segment that defines the data function.
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// InputModel is a marshalled JSON schema describing the accepted input.
	// This model must be satisfied by the execution model of the owning workflow.
	InputModel string `protobuf:"bytes,3,opt,name=inputModel,proto3" json:"inputModel,omitempty"`
	// OutputModel is a marshalled JSON schema describing a single output record.
	// The data function produces an array of this schema, streamed to the
	// orchestrator for caching. Validated once at retrieval time.
	OutputModel string `protobuf:"bytes,4,opt,name=outputModel,proto3" json:"outputModel,omitempty"`
	// Settings governs the lifecycle and retention of data produced by this
	// data function.
	Settings      *DataFunctionSettings `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFunction) Reset() {
	*x = DataFunction{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFunction) ProtoMessage() {}

func (x *DataFunction) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFunction.ProtoReflect.Descriptor instead.
func (*DataFunction) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *DataFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataFunction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DataFunction) GetInputModel() string {
	if x != nil {
		return x.InputModel
	}
	return ""
}

func (x *DataFunction) GetOutputModel() string {
	if x != nil {
		return x.OutputModel
	}
	return ""
}

func (x *DataFunction) GetSettings() *DataFunctionSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Task defines a registered task and its execution configuration.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TaskHash is the hash of the AST segment corresponding to this task.
	TaskHash string `protobuf:"bytes,1,opt,name=taskHash,proto3" json:"taskHash,omitempty"`
	// Name is the unique name of this task.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description is a human-readable summary of the task's purpose.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// ExecutionSettings governs execution timeouts, retries, backoff, and SLA deadlines.
	ExecutionSettings *TaskExecutionSettings `protobuf:"bytes,4,opt,name=executionSettings,proto3" json:"executionSettings,omitempty"`
	// InputModel is a marshalled JSON schema (JSON Schema Standard) describing
	// the task's accepted input. Validation and pointer extensions are not enforced.
	InputModel string `protobuf:"bytes,5,opt,name=inputModel,proto3" json:"inputModel,omitempty"`
	// OutputModel is a marshalled JSON schema (JSON Schema Standard) describing
	// the task's output. Validation and pointer extensions are not enforced.
	OutputModel string `protobuf:"bytes,6,opt,name=outputModel,proto3" json:"outputModel,omitempty"`
	// RequiredDataFunctions lists all data functions this task depends on.
	RequiredDataFunctions []string `protobuf:"bytes,7,rep,name=requiredDataFunctions,proto3" json:"requiredDataFunctions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskHash() string {
	if x != nil {
		return x.TaskHash
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetExecutionSettings() *TaskExecutionSettings {
	if x != nil {
		return x.ExecutionSettings
	}
	return nil
}

func (x *Task) GetInputModel() string {
	if x != nil {
		return x.InputModel
	}
	return ""
}

func (x *Task) GetOutputModel() string {
	if x != nil {
		return x.OutputModel
	}
	return ""
}

func (x *Task) GetRequiredDataFunctions() []string {
	if x != nil {
		return x.RequiredDataFunctions
	}
	return nil
}

// WorkflowEdge defines the relationship between two tasks in the workflow.
// Edges are combined to form a workflow, or DAG.
type WorkflowEdge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the task going from
	FromTaskName string `protobuf:"bytes,1,opt,name=fromTaskName,proto3" json:"fromTaskName,omitempty"`
	// The hash of the AST segment of the task
	FromTaskHash string `protobuf:"bytes,2,opt,name=fromTaskHash,proto3" json:"fromTaskHash,omitempty"`
	// The worker that implements the task
	FromTaskWorker string `protobuf:"bytes,3,opt,name=fromTaskWorker,proto3" json:"fromTaskWorker,omitempty"`
	// The name of the task going from
	ToTaskName string `protobuf:"bytes,4,opt,name=toTaskName,proto3" json:"toTaskName,omitempty"`
	// The hash of the AST segment of the task
	ToTaskHash string `protobuf:"bytes,5,opt,name=toTaskHash,proto3" json:"toTaskHash,omitempty"`
	// The worker that implements the task
	ToTaskWorker  string `protobuf:"bytes,6,opt,name=toTaskWorker,proto3" json:"toTaskWorker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEdge) Reset() {
	*x = WorkflowEdge{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEdge) ProtoMessage() {}

func (x *WorkflowEdge) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEdge.ProtoReflect.Descriptor instead.
func (*WorkflowEdge) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowEdge) GetFromTaskName() string {
	if x != nil {
		return x.FromTaskName
	}
	return ""
}

func (x *WorkflowEdge) GetFromTaskHash() string {
	if x != nil {
		return x.FromTaskHash
	}
	return ""
}

func (x *WorkflowEdge) GetFromTaskWorker() string {
	if x != nil {
		return x.FromTaskWorker
	}
	return ""
}

func (x *WorkflowEdge) GetToTaskName() string {
	if x != nil {
		return x.ToTaskName
	}
	return ""
}

func (x *WorkflowEdge) GetToTaskHash() string {
	if x != nil {
		return x.ToTaskHash
	}
	return ""
}

func (x *WorkflowEdge) GetToTaskWorker() string {
	if x != nil {
		return x.ToTaskWorker
	}
	return ""
}

// Workflow defines a registered workflow, its task graph, and runtime settings.
type Workflow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkflowName is the globally unique string identifier for this workflow.
	WorkflowName string `protobuf:"bytes,1,opt,name=workflowName,proto3" json:"workflowName,omitempty"`
	// Description is a human-readable explanation of the workflow's purpose.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// WorkflowHash is a hash of the workflow structure, factoring in tasks,
	// dependencies, and execution models.
	WorkflowHash string `protobuf:"bytes,3,opt,name=workflowHash,proto3" json:"workflowHash,omitempty"`
	// Edges defines the dependency relationships between tasks in this workflow.
	Edges []*WorkflowEdge `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	// ExecutionSettings defines concurrency limits and task prioritisation.
	ExecutionSettings *WorkflowExecutionSettings `protobuf:"bytes,5,opt,name=executionSettings,proto3" json:"executionSettings,omitempty"`
	// InputModel is a marshalled JSON schema describing the
	// parameters that must be provided at workflow trigger time.
	InputModel string `protobuf:"bytes,6,opt,name=inputModel,proto3" json:"inputModel,omitempty"`
	// HaltOnFailure instructs the orchestrator to stop parallel task execution
	// if any task encounters a failure.
	HaltOnFailure bool `protobuf:"varint,7,opt,name=haltOnFailure,proto3" json:"haltOnFailure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *Workflow) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetWorkflowHash() string {
	if x != nil {
		return x.WorkflowHash
	}
	return ""
}

func (x *Workflow) GetEdges() []*WorkflowEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Workflow) GetExecutionSettings() *WorkflowExecutionSettings {
	if x != nil {
		return x.ExecutionSettings
	}
	return nil
}

func (x *Workflow) GetInputModel() string {
	if x != nil {
		return x.InputModel
	}
	return ""
}

func (x *Workflow) GetHaltOnFailure() bool {
	if x != nil {
		return x.HaltOnFailure
	}
	return false
}

// ============================================================
// RegisterWorker RPC
// ============================================================
type RegisterWorkerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public of the worker
	PublicKey     string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// RegisterWorkerResponse is the response message for the Registercodebase RPC.
type RegisterWorkerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status indicates whether registration succeeded or failed.
	Status RegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=RegistrationStatus" json:"status,omitempty"`
	// Message provides detail on why registration failed, if applicable.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The unique worker Id
	WorkerId      string `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterWorkerResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterWorkerResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// ============================================================
// GetNonce RPC
// ============================================================
type GetNonceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the worker
	WorkerId      string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceRequest) Reset() {
	*x = GetNonceRequest{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceRequest) ProtoMessage() {}

func (x *GetNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceRequest.ProtoReflect.Descriptor instead.
func (*GetNonceRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *GetNonceRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetNonceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status indicates whether get nonce succeeded or failed.
	Status RegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=RegistrationStatus" json:"status,omitempty"`
	// Message provides detail on why registration failed, if applicable.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// A challenge that the worker needs to sign
	Challenge     []byte `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceResponse) Reset() {
	*x = GetNonceResponse{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceResponse) ProtoMessage() {}

func (x *GetNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceResponse.ProtoReflect.Descriptor instead.
func (*GetNonceResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetNonceResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *GetNonceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetNonceResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// ============================================================
// CheckNonce RPC
// ============================================================
type CheckNonceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the response to the challenge
	SignedChallenge []byte `protobuf:"bytes,1,opt,name=signed_challenge,json=signedChallenge,proto3" json:"signed_challenge,omitempty"`
	// The worker ID
	WorkerId      string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNonceRequest) Reset() {
	*x = CheckNonceRequest{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNonceRequest) ProtoMessage() {}

func (x *CheckNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNonceRequest.ProtoReflect.Descriptor instead.
func (*CheckNonceRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *CheckNonceRequest) GetSignedChallenge() []byte {
	if x != nil {
		return x.SignedChallenge
	}
	return nil
}

func (x *CheckNonceRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type CheckNonceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status indicates whether get nonce check succeeded or failed.
	Status RegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=RegistrationStatus" json:"status,omitempty"`
	// Message provides detail on why it failed, if applicable.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Access key expiry datetime
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// A short lived access key
	AccessKey     string `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNonceResponse) Reset() {
	*x = CheckNonceResponse{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNonceResponse) ProtoMessage() {}

func (x *CheckNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNonceResponse.ProtoReflect.Descriptor instead.
func (*CheckNonceResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *CheckNonceResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *CheckNonceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckNonceResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CheckNonceResponse) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

// ============================================================
// RegisterWorkerSnapshot RPC
// ============================================================
type RegisterWorkerSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the globally unique ID of the worker
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// GitCommitHash is the current git commit
	GitCommitHash string `protobuf:"bytes,2,opt,name=gitCommitHash,proto3" json:"gitCommitHash,omitempty"`
	// Datafunctions is an array of data functions
	DataFunctions []*DataFunction `protobuf:"bytes,3,rep,name=dataFunctions,proto3" json:"dataFunctions,omitempty"`
	// Tasks is an array of tasks
	Tasks []*Task `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// Workflows is an array of workflows
	Workflows     []*Workflow `protobuf:"bytes,5,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerSnapshotRequest) Reset() {
	*x = RegisterWorkerSnapshotRequest{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerSnapshotRequest) ProtoMessage() {}

func (x *RegisterWorkerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterWorkerSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterWorkerSnapshotRequest) GetGitCommitHash() string {
	if x != nil {
		return x.GitCommitHash
	}
	return ""
}

func (x *RegisterWorkerSnapshotRequest) GetDataFunctions() []*DataFunction {
	if x != nil {
		return x.DataFunctions
	}
	return nil
}

func (x *RegisterWorkerSnapshotRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *RegisterWorkerSnapshotRequest) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

// RegisterWorkerResponse is the response message for the Registercodebase RPC.
type RegisterWorkerSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status indicates whether registration succeeded or failed.
	Status RegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=RegistrationStatus" json:"status,omitempty"`
	// Message provides detail on why registration failed, if applicable.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerSnapshotResponse) Reset() {
	*x = RegisterWorkerSnapshotResponse{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerSnapshotResponse) ProtoMessage() {}

func (x *RegisterWorkerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterWorkerSnapshotResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *RegisterWorkerSnapshotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ============================================================
// RegisterServingStatus RPC
// ============================================================
// RegisterServingStatus message
type RegisterServingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the worker
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Connection URL from the perspective of the core orchestrator
	ConnectionUrl string `protobuf:"bytes,2,opt,name=connectionUrl,proto3" json:"connectionUrl,omitempty"`
	// Explicit flag stating whether the worker is serving
	IsServing     bool `protobuf:"varint,3,opt,name=isServing,proto3" json:"isServing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServingRequest) Reset() {
	*x = RegisterServingRequest{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServingRequest) ProtoMessage() {}

func (x *RegisterServingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServingRequest.ProtoReflect.Descriptor instead.
func (*RegisterServingRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterServingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterServingRequest) GetConnectionUrl() string {
	if x != nil {
		return x.ConnectionUrl
	}
	return ""
}

func (x *RegisterServingRequest) GetIsServing() bool {
	if x != nil {
		return x.IsServing
	}
	return false
}

// RegisterServingResponse message
type RegisterServingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status indicates whether registration succeeded or failed.
	Status RegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=RegistrationStatus" json:"status,omitempty"`
	// Message provides detail on why registration failed, if applicable.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServingResponse) Reset() {
	*x = RegisterServingResponse{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServingResponse) ProtoMessage() {}

func (x *RegisterServingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServingResponse.ProtoReflect.Descriptor instead.
func (*RegisterServingResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterServingResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *RegisterServingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TriggerWorkflowRequest is the request message for the TriggerWorkflow RPC.
type TriggerWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkflowName identifies the target workflow to execute.
	WorkflowName string `protobuf:"bytes,1,opt,name=workflowName,proto3" json:"workflowName,omitempty"`
	// LogicalDate is the target execution timestamp. If unset, execution is immediate.
	LogicalDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=logicalDate,proto3,oneof" json:"logicalDate,omitempty"`
	// ExecutionParameters is a marshalled JSON struct of runtime parameters,
	// conforming to the workflow's ExecutionParametersModel schema.
	ExecutionParameters string `protobuf:"bytes,3,opt,name=executionParameters,proto3" json:"executionParameters,omitempty"`
	// TriggerSource identifies the origin of this trigger event.
	TriggerSource TriggerSource `protobuf:"varint,4,opt,name=triggerSource,proto3,enum=TriggerSource" json:"triggerSource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerWorkflowRequest) Reset() {
	*x = TriggerWorkflowRequest{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWorkflowRequest) ProtoMessage() {}

func (x *TriggerWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWorkflowRequest.ProtoReflect.Descriptor instead.
func (*TriggerWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *TriggerWorkflowRequest) GetLogicalDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LogicalDate
	}
	return nil
}

func (x *TriggerWorkflowRequest) GetExecutionParameters() string {
	if x != nil {
		return x.ExecutionParameters
	}
	return ""
}

func (x *TriggerWorkflowRequest) GetTriggerSource() TriggerSource {
	if x != nil {
		return x.TriggerSource
	}
	return TriggerSource_TRIGGER_SOURCE_UNSPECIFIED
}

// TriggerWorkflowResponse is the response message for the TriggerWorkflow RPC.
type TriggerWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkflowRunID is the unique runtime execution tracker generated by the
	// orchestrator for this run.
	WorkflowRunId string `protobuf:"bytes,1,opt,name=workflowRunId,proto3" json:"workflowRunId,omitempty"`
	// Status indicates whether the trigger was accepted or rejected.
	Status TriggerStatus `protobuf:"varint,2,opt,name=status,proto3,enum=TriggerStatus" json:"status,omitempty"`
	// Message provides detail on parameter or trigger validation failures.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerWorkflowResponse) Reset() {
	*x = TriggerWorkflowResponse{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWorkflowResponse) ProtoMessage() {}

func (x *TriggerWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWorkflowResponse.ProtoReflect.Descriptor instead.
func (*TriggerWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerWorkflowResponse) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *TriggerWorkflowResponse) GetStatus() TriggerStatus {
	if x != nil {
		return x.Status
	}
	return TriggerStatus_TRIGGER_STATUS_UNSPECIFIED
}

func (x *TriggerWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RegisterDataFunctionCompletionRequest is the request message for the
// RegisterDataFunctionCompletion RPC.
type RegisterDataFunctionCompletionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkflowRunID is the ID of the workflow run that invoked the data function.
	WorkflowRunId string `protobuf:"bytes,1,opt,name=workflowRunId,proto3" json:"workflowRunId,omitempty"`
	// Status indicates whether the data function completed successfully or failed.
	Status ExecutionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ExecutionStatus" json:"status,omitempty"`
	// Message is a client-provided description of the failure, ideally including
	// a full stack trace.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDataFunctionCompletionRequest) Reset() {
	*x = RegisterDataFunctionCompletionRequest{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDataFunctionCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataFunctionCompletionRequest) ProtoMessage() {}

func (x *RegisterDataFunctionCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataFunctionCompletionRequest.ProtoReflect.Descriptor instead.
func (*RegisterDataFunctionCompletionRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterDataFunctionCompletionRequest) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *RegisterDataFunctionCompletionRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *RegisterDataFunctionCompletionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RegisterDataFunctionCompletionResponse is the response message for the
// RegisterDataFunctionCompletion RPC. Currently carries no fields.
type RegisterDataFunctionCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDataFunctionCompletionResponse) Reset() {
	*x = RegisterDataFunctionCompletionResponse{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDataFunctionCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataFunctionCompletionResponse) ProtoMessage() {}

func (x *RegisterDataFunctionCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataFunctionCompletionResponse.ProtoReflect.Descriptor instead.
func (*RegisterDataFunctionCompletionResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

// RegisterTaskResultRequest is the request message for the RegisterTaskResult RPC.
type RegisterTaskResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkflowRunID is the ID of the workflow run this result belongs to.
	WorkflowRunId string `protobuf:"bytes,1,opt,name=workflowRunId,proto3" json:"workflowRunId,omitempty"`
	// TaskName is the name of the task within the workflow.
	TaskName string `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`
	// Result is the task's output as a marshalled JSON object. Validated on retrieval.
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Status indicates whether the task completed successfully or failed.
	Status ExecutionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=ExecutionStatus" json:"status,omitempty"`
	// Message is the failure description produced by the worker, ideally a full
	// stack trace.
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// ComputeMetrics captures the CPU and memory resources consumed by this task.
	ComputeMetrics *ComputeMetrics `protobuf:"bytes,6,opt,name=computeMetrics,proto3" json:"computeMetrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterTaskResultRequest) Reset() {
	*x = RegisterTaskResultRequest{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskResultRequest) ProtoMessage() {}

func (x *RegisterTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskResultRequest.ProtoReflect.Descriptor instead.
func (*RegisterTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterTaskResultRequest) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *RegisterTaskResultRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *RegisterTaskResultRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RegisterTaskResultRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *RegisterTaskResultRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterTaskResultRequest) GetComputeMetrics() *ComputeMetrics {
	if x != nil {
		return x.ComputeMetrics
	}
	return nil
}

// RegisterTaskResultResponse is the response message for the RegisterTaskResult RPC.
// Currently carries no fields.
type RegisterTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskResultResponse) Reset() {
	*x = RegisterTaskResultResponse{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskResultResponse) ProtoMessage() {}

func (x *RegisterTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskResultResponse.ProtoReflect.Descriptor instead.
func (*RegisterTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

// ExposeStateRequest is the request message for the ExposeState RPC.
type ExposeStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GitCommitHash, if provided, returns state as of that specific commit.
	// Takes priority over Timestamp when both are set.
	GitCommitHash *string `protobuf:"bytes,1,opt,name=gitCommitHash,proto3,oneof" json:"gitCommitHash,omitempty"`
	// Timestamp, if provided, returns state as of the closest commit to that time.
	// Ignored if GitCommitHash is set.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	// Codebase, if provided, filters out all assets (Tasks, Workflows,
	// DataFunctions, etc.) registered under this codebase from the response.
	Codebase      *string `protobuf:"bytes,3,opt,name=codebase,proto3,oneof" json:"codebase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposeStateRequest) Reset() {
	*x = ExposeStateRequest{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeStateRequest) ProtoMessage() {}

func (x *ExposeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeStateRequest.ProtoReflect.Descriptor instead.
func (*ExposeStateRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *ExposeStateRequest) GetGitCommitHash() string {
	if x != nil && x.GitCommitHash != nil {
		return *x.GitCommitHash
	}
	return ""
}

func (x *ExposeStateRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExposeStateRequest) GetCodebase() string {
	if x != nil && x.Codebase != nil {
		return *x.Codebase
	}
	return ""
}

// ExposeStateResponse is the response message for the ExposeState RPC.
type ExposeStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tasks is the array of registered tasks matching the requested state.
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// Workflows is the array of registered workflows and their task references.
	Workflows []*Workflow `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	// DataFunctions is the array of registered data functions.
	DataFunctions []*DataFunction `protobuf:"bytes,3,rep,name=dataFunctions,proto3" json:"dataFunctions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposeStateResponse) Reset() {
	*x = ExposeStateResponse{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposeStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeStateResponse) ProtoMessage() {}

func (x *ExposeStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeStateResponse.ProtoReflect.Descriptor instead.
func (*ExposeStateResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

func (x *ExposeStateResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ExposeStateResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ExposeStateResponse) GetDataFunctions() []*DataFunction {
	if x != nil {
		return x.DataFunctions
	}
	return nil
}

// ============================================================
// QueryTaskResult RPC
// ============================================================
//
// The top-level request message for QueryTaskResult.
type QueryTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the task to return results for.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Filters applied to execution parameters. Groups are AND-ed together.
	ExecutionParameterFilters []*FilterGroup `protobuf:"bytes,2,rep,name=execution_parameter_filters,json=executionParameterFilters,proto3" json:"execution_parameter_filters,omitempty"`
	// Filters applied to task results. Groups are AND-ed together.
	ResultFilters []*FilterGroup `protobuf:"bytes,3,rep,name=result_filters,json=resultFilters,proto3" json:"result_filters,omitempty"`
	// Defines how results should be sorted. Evaluated in order.
	OrderBy []*OrderByStatement `protobuf:"bytes,4,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// If set, only these keys will be included in each result's payload.
	ResultFields []string `protobuf:"bytes,5,rep,name=result_fields,json=resultFields,proto3" json:"result_fields,omitempty"`
	// The maximum number of results to return. Required.
	PageSize int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token from a previous response. Omit on the first request.
	PageToken     *string `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskRequest) Reset() {
	*x = QueryTaskRequest{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskRequest) ProtoMessage() {}

func (x *QueryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskRequest.ProtoReflect.Descriptor instead.
func (*QueryTaskRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *QueryTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryTaskRequest) GetExecutionParameterFilters() []*FilterGroup {
	if x != nil {
		return x.ExecutionParameterFilters
	}
	return nil
}

func (x *QueryTaskRequest) GetResultFilters() []*FilterGroup {
	if x != nil {
		return x.ResultFilters
	}
	return nil
}

func (x *QueryTaskRequest) GetOrderBy() []*OrderByStatement {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *QueryTaskRequest) GetResultFields() []string {
	if x != nil {
		return x.ResultFields
	}
	return nil
}

func (x *QueryTaskRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryTaskRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

// The top-level response message for QueryTaskResult.
type QueryTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matched task results.
	Results []*TaskResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Opaque token to pass as page_token in the next request.
	// Absent if there are no further results.
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskResponse) Reset() {
	*x = QueryTaskResponse{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskResponse) ProtoMessage() {}

func (x *QueryTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskResponse.ProtoReflect.Descriptor instead.
func (*QueryTaskResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{23}
}

func (x *QueryTaskResponse) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryTaskResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

// A single task result entry.
type TaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the task.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The execution parameters that triggered this task, as a marshalled JSON string.
	ExecutionParameters string `protobuf:"bytes,2,opt,name=execution_parameters,json=executionParameters,proto3" json:"execution_parameters,omitempty"`
	// The task result, as a marshalled JSON string.
	// If result_fields was set on the request, only those fields will be present.
	Result        string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{24}
}

func (x *TaskResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskResult) GetExecutionParameters() string {
	if x != nil {
		return x.ExecutionParameters
	}
	return ""
}

func (x *TaskResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// A set of LeafFilters joined by OR. All FilterGroups in a list are AND-ed together.
type FilterGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// At least one filter must match for this group to be satisfied.
	Filters       []*LeafFilter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterGroup) Reset() {
	*x = FilterGroup{}
	mi := &file_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterGroup) ProtoMessage() {}

func (x *FilterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterGroup.ProtoReflect.Descriptor instead.
func (*FilterGroup) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{25}
}

func (x *FilterGroup) GetFilters() []*LeafFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// A single condition evaluated against one KV pair.
type LeafFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to filter on.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The comparison operation to apply.
	Comparator Comparator `protobuf:"varint,2,opt,name=comparator,proto3,enum=Comparator" json:"comparator,omitempty"`
	// The value(s) to compare against.
	// Omit for EXISTS and NOT_EXISTS.
	// Populate values (not value) for IN and NOT_IN.
	//
	// Types that are valid to be assigned to ValueOneof:
	//
	//	*LeafFilter_Value
	//	*LeafFilter_Values
	ValueOneof    isLeafFilter_ValueOneof `protobuf_oneof:"value_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeafFilter) Reset() {
	*x = LeafFilter{}
	mi := &file_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeafFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafFilter) ProtoMessage() {}

func (x *LeafFilter) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafFilter.ProtoReflect.Descriptor instead.
func (*LeafFilter) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{26}
}

func (x *LeafFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LeafFilter) GetComparator() Comparator {
	if x != nil {
		return x.Comparator
	}
	return Comparator_COMPARATOR_UNSPECIFIED
}

func (x *LeafFilter) GetValueOneof() isLeafFilter_ValueOneof {
	if x != nil {
		return x.ValueOneof
	}
	return nil
}

func (x *LeafFilter) GetValue() string {
	if x != nil {
		if x, ok := x.ValueOneof.(*LeafFilter_Value); ok {
			return x.Value
		}
	}
	return ""
}

func (x *LeafFilter) GetValues() *StringList {
	if x != nil {
		if x, ok := x.ValueOneof.(*LeafFilter_Values); ok {
			return x.Values
		}
	}
	return nil
}

type isLeafFilter_ValueOneof interface {
	isLeafFilter_ValueOneof()
}

type LeafFilter_Value struct {
	Value string `protobuf:"bytes,3,opt,name=value,proto3,oneof"` // For EQ, NEQ, GT, GTE, LT, LTE, CONTAINS, PREFIX
}

type LeafFilter_Values struct {
	Values *StringList `protobuf:"bytes,4,opt,name=values,proto3,oneof"` // For IN, NOT_IN
}

func (*LeafFilter_Value) isLeafFilter_ValueOneof() {}

func (*LeafFilter_Values) isLeafFilter_ValueOneof() {}

// A wrapper for a list of strings, used for IN / NOT_IN comparators.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{27}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Defines a single sort statement.
type OrderByStatement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to sort by.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Which table the key belongs to.
	Source DataSource `protobuf:"varint,2,opt,name=source,proto3,enum=DataSource" json:"source,omitempty"`
	// The sort direction.
	Direction     SortDirection `protobuf:"varint,3,opt,name=direction,proto3,enum=SortDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderByStatement) Reset() {
	*x = OrderByStatement{}
	mi := &file_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderByStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderByStatement) ProtoMessage() {}

func (x *OrderByStatement) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderByStatement.ProtoReflect.Descriptor instead.
func (*OrderByStatement) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{28}
}

func (x *OrderByStatement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OrderByStatement) GetSource() DataSource {
	if x != nil {
		return x.Source
	}
	return DataSource_DATA_SOURCE_UNSPECIFIED
}

func (x *OrderByStatement) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fshared.proto\"\xab\x01\n" +
	"\fDataFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1e\n" +
	"\n" +
	"inputModel\x18\x03 \x01(\tR\n" +
	"inputModel\x12 \n" +
	"\voutputModel\x18\x04 \x01(\tR\voutputModel\x121\n" +
	"\bsettings\x18\x05 \x01(\v2\x15.DataFunctionSettingsR\bsettings\"\x96\x02\n" +
	"\x04Task\x12\x1a\n" +
	"\btaskHash\x18\x01 \x01(\tR\btaskHash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12D\n" +
	"\x11executionSettings\x18\x04 \x01(\v2\x16.TaskExecutionSettingsR\x11executionSettings\x12\x1e\n" +
	"\n" +
	"inputModel\x18\x05 \x01(\tR\n" +
	"inputModel\x12 \n" +
	"\voutputModel\x18\x06 \x01(\tR\voutputModel\x124\n" +
	"\x15requiredDataFunctions\x18\a \x03(\tR\x15requiredDataFunctions\"\xe2\x01\n" +
	"\fWorkflowEdge\x12\"\n" +
	"\ffromTaskName\x18\x01 \x01(\tR\ffromTaskName\x12\"\n" +
	"\ffromTaskHash\x18\x02 \x01(\tR\ffromTaskHash\x12&\n" +
	"\x0efromTaskWorker\x18\x03 \x01(\tR\x0efromTaskWorker\x12\x1e\n" +
	"\n" +
	"toTaskName\x18\x04 \x01(\tR\n" +
	"toTaskName\x12\x1e\n" +
	"\n" +
	"toTaskHash\x18\x05 \x01(\tR\n" +
	"toTaskHash\x12\"\n" +
	"\ftoTaskWorker\x18\x06 \x01(\tR\ftoTaskWorker\"\xa9\x02\n" +
	"\bWorkflow\x12\"\n" +
	"\fworkflowName\x18\x01 \x01(\tR\fworkflowName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\fworkflowHash\x18\x03 \x01(\tR\fworkflowHash\x12#\n" +
	"\x05edges\x18\x04 \x03(\v2\r.WorkflowEdgeR\x05edges\x12H\n" +
	"\x11executionSettings\x18\x05 \x01(\v2\x1a.WorkflowExecutionSettingsR\x11executionSettings\x12\x1e\n" +
	"\n" +
	"inputModel\x18\x06 \x01(\tR\n" +
	"inputModel\x12$\n" +
	"\rhaltOnFailure\x18\a \x01(\bR\rhaltOnFailure\"6\n" +
	"\x15RegisterWorkerRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"|\n" +
	"\x16RegisterWorkerResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.RegistrationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\".\n" +
	"\x0fGetNonceRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"w\n" +
	"\x10GetNonceResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.RegistrationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\fR\tchallenge\"[\n" +
	"\x11CheckNonceRequest\x12)\n" +
	"\x10signed_challenge\x18\x01 \x01(\fR\x0fsignedChallenge\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"\xb5\x01\n" +
	"\x12CheckNonceResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.RegistrationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"access_key\x18\x04 \x01(\tR\taccessKey\"\xd0\x01\n" +
	"\x1dRegisterWorkerSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\rgitCommitHash\x18\x02 \x01(\tR\rgitCommitHash\x123\n" +
	"\rdataFunctions\x18\x03 \x03(\v2\r.DataFunctionR\rdataFunctions\x12\x1b\n" +
	"\x05tasks\x18\x04 \x03(\v2\x05.TaskR\x05tasks\x12'\n" +
	"\tworkflows\x18\x05 \x03(\v2\t.WorkflowR\tworkflows\"g\n" +
	"\x1eRegisterWorkerSnapshotResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.RegistrationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x16RegisterServingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\rconnectionUrl\x18\x02 \x01(\tR\rconnectionUrl\x12\x1c\n" +
	"\tisServing\x18\x03 \x01(\bR\tisServing\"`\n" +
	"\x17RegisterServingResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.RegistrationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf7\x01\n" +
	"\x16TriggerWorkflowRequest\x12\"\n" +
	"\fworkflowName\x18\x01 \x01(\tR\fworkflowName\x12A\n" +
	"\vlogicalDate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vlogicalDate\x88\x01\x01\x120\n" +
	"\x13executionParameters\x18\x03 \x01(\tR\x13executionParameters\x124\n" +
	"\rtriggerSource\x18\x04 \x01(\x0e2\x0e.TriggerSourceR\rtriggerSourceB\x0e\n" +
	"\f_logicalDate\"\x81\x01\n" +
	"\x17TriggerWorkflowResponse\x12$\n" +
	"\rworkflowRunId\x18\x01 \x01(\tR\rworkflowRunId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.TriggerStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x91\x01\n" +
	"%RegisterDataFunctionCompletionRequest\x12$\n" +
	"\rworkflowRunId\x18\x01 \x01(\tR\rworkflowRunId\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.ExecutionStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"(\n" +
	"&RegisterDataFunctionCompletionResponse\"\xf2\x01\n" +
	"\x19RegisterTaskResultRequest\x12$\n" +
	"\rworkflowRunId\x18\x01 \x01(\tR\rworkflowRunId\x12\x1a\n" +
	"\btaskName\x18\x02 \x01(\tR\btaskName\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.ExecutionStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x127\n" +
	"\x0ecomputeMetrics\x18\x06 \x01(\v2\x0f.ComputeMetricsR\x0ecomputeMetrics\"\x1c\n" +
	"\x1aRegisterTaskResultResponse\"\xcc\x01\n" +
	"\x12ExposeStateRequest\x12)\n" +
	"\rgitCommitHash\x18\x01 \x01(\tH\x00R\rgitCommitHash\x88\x01\x01\x12=\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\ttimestamp\x88\x01\x01\x12\x1f\n" +
	"\bcodebase\x18\x03 \x01(\tH\x02R\bcodebase\x88\x01\x01B\x10\n" +
	"\x0e_gitCommitHashB\f\n" +
	"\n" +
	"_timestampB\v\n" +
	"\t_codebase\"\x90\x01\n" +
	"\x13ExposeStateResponse\x12\x1b\n" +
	"\x05tasks\x18\x01 \x03(\v2\x05.TaskR\x05tasks\x12'\n" +
	"\tworkflows\x18\x02 \x03(\v2\t.WorkflowR\tworkflows\x123\n" +
	"\rdataFunctions\x18\x03 \x03(\v2\r.DataFunctionR\rdataFunctions\"\xcc\x02\n" +
	"\x10QueryTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12L\n" +
	"\x1bexecution_parameter_filters\x18\x02 \x03(\v2\f.FilterGroupR\x19executionParameterFilters\x123\n" +
	"\x0eresult_filters\x18\x03 \x03(\v2\f.FilterGroupR\rresultFilters\x12,\n" +
	"\border_by\x18\x04 \x03(\v2\x11.OrderByStatementR\aorderBy\x12#\n" +
	"\rresult_fields\x18\x05 \x03(\tR\fresultFields\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\a \x01(\tH\x00R\tpageToken\x88\x01\x01B\r\n" +
	"\v_page_token\"{\n" +
	"\x11QueryTaskResponse\x12%\n" +
	"\aresults\x18\x01 \x03(\v2\v.TaskResultR\aresults\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"k\n" +
	"\n" +
	"TaskResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x14execution_parameters\x18\x02 \x01(\tR\x13executionParameters\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"4\n" +
	"\vFilterGroup\x12%\n" +
	"\afilters\x18\x01 \x03(\v2\v.LeafFilterR\afilters\"\x99\x01\n" +
	"\n" +
	"LeafFilter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\n" +
	"comparator\x18\x02 \x01(\x0e2\v.ComparatorR\n" +
	"comparator\x12\x16\n" +
	"\x05value\x18\x03 \x01(\tH\x00R\x05value\x12%\n" +
	"\x06values\x18\x04 \x01(\v2\v.StringListH\x00R\x06valuesB\r\n" +
	"\vvalue_oneof\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"w\n" +
	"\x10OrderByStatement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x06source\x18\x02 \x01(\x0e2\v.DataSourceR\x06source\x12,\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x0e.SortDirectionR\tdirection*\xa5\x01\n" +
	"\n" +
	"Comparator\x12\x1a\n" +
	"\x16COMPARATOR_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02EQ\x10\x01\x12\a\n" +
	"\x03NEQ\x10\x02\x12\x06\n" +
	"\x02GT\x10\x03\x12\a\n" +
	"\x03GTE\x10\x04\x12\x06\n" +
	"\x02LT\x10\x05\x12\a\n" +
	"\x03LTE\x10\x06\x12\x06\n" +
	"\x02IN\x10\a\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\b\x12\n" +
	"\n" +
	"\x06EXISTS\x10\t\x12\x0e\n" +
	"\n" +
	"NOT_EXISTS\x10\n" +
	"\x12\f\n" +
	"\bCONTAINS\x10\v\x12\n" +
	"\n" +
	"\x06PREFIX\x10\f*O\n" +
	"\n" +
	"DataSource\x12\x1b\n" +
	"\x17DATA_SOURCE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06RESULT\x10\x01\x12\x18\n" +
	"\x14EXECUTION_PARAMETERS\x10\x02*B\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ASC\x10\x01\x12\b\n" +
	"\x04DESC\x10\x022\xcc\x05\n" +
	"\x04Core\x12A\n" +
	"\x0eRegisterWorker\x12\x16.RegisterWorkerRequest\x1a\x17.RegisterWorkerResponse\x12/\n" +
	"\bGetNonce\x12\x10.GetNonceRequest\x1a\x11.GetNonceResponse\x125\n" +
	"\n" +
	"CheckNonce\x12\x12.CheckNonceRequest\x1a\x13.CheckNonceResponse\x12Y\n" +
	"\x16RegisterWorkerSnapshot\x12\x1e.RegisterWorkerSnapshotRequest\x1a\x1f.RegisterWorkerSnapshotResponse\x12D\n" +
	"\x0fRegisterServing\x12\x17.RegisterServingRequest\x1a\x18.RegisterServingResponse\x12D\n" +
	"\x0fTriggerWorkflow\x12\x17.TriggerWorkflowRequest\x1a\x18.TriggerWorkflowResponse\x12m\n" +
	"\x1aRegisterDataFunctionResult\x12&.RegisterDataFunctionCompletionRequest\x1a'.RegisterDataFunctionCompletionResponse\x12M\n" +
	"\x12RegisterTaskResult\x12\x1a.RegisterTaskResultRequest\x1a\x1b.RegisterTaskResultResponse\x128\n" +
	"\vExposeState\x12\x13.ExposeStateRequest\x1a\x14.ExposeStateResponse\x12:\n" +
	"\x0fQueryTaskResult\x12\x11.QueryTaskRequest\x1a\x12.QueryTaskResponse0\x01B*Z(github.com/orca-telemetry/contract/go/v2b\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_core_proto_goTypes = []any{
	(Comparator)(0),                                // 0: Comparator
	(DataSource)(0),                                // 1: DataSource
	(SortDirection)(0),                             // 2: SortDirection
	(*DataFunction)(nil),                           // 3: DataFunction
	(*Task)(nil),                                   // 4: Task
	(*WorkflowEdge)(nil),                           // 5: WorkflowEdge
	(*Workflow)(nil),                               // 6: Workflow
	(*RegisterWorkerRequest)(nil),                  // 7: RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),                 // 8: RegisterWorkerResponse
	(*GetNonceRequest)(nil),                        // 9: GetNonceRequest
	(*GetNonceResponse)(nil),                       // 10: GetNonceResponse
	(*CheckNonceRequest)(nil),                      // 11: CheckNonceRequest
	(*CheckNonceResponse)(nil),                     // 12: CheckNonceResponse
	(*RegisterWorkerSnapshotRequest)(nil),          // 13: RegisterWorkerSnapshotRequest
	(*RegisterWorkerSnapshotResponse)(nil),         // 14: RegisterWorkerSnapshotResponse
	(*RegisterServingRequest)(nil),                 // 15: RegisterServingRequest
	(*RegisterServingResponse)(nil),                // 16: RegisterServingResponse
	(*TriggerWorkflowRequest)(nil),                 // 17: TriggerWorkflowRequest
	(*TriggerWorkflowResponse)(nil),                // 18: TriggerWorkflowResponse
	(*RegisterDataFunctionCompletionRequest)(nil),  // 19: RegisterDataFunctionCompletionRequest
	(*RegisterDataFunctionCompletionResponse)(nil), // 20: RegisterDataFunctionCompletionResponse
	(*RegisterTaskResultRequest)(nil),              // 21: RegisterTaskResultRequest
	(*RegisterTaskResultResponse)(nil),             // 22: RegisterTaskResultResponse
	(*ExposeStateRequest)(nil),                     // 23: ExposeStateRequest
	(*ExposeStateResponse)(nil),                    // 24: ExposeStateResponse
	(*QueryTaskRequest)(nil),                       // 25: QueryTaskRequest
	(*QueryTaskResponse)(nil),                      // 26: QueryTaskResponse
	(*TaskResult)(nil),                             // 27: TaskResult
	(*FilterGroup)(nil),                            // 28: FilterGroup
	(*LeafFilter)(nil),                             // 29: LeafFilter
	(*StringList)(nil),                             // 30: StringList
	(*OrderByStatement)(nil),                       // 31: OrderByStatement
	(*DataFunctionSettings)(nil),                   // 32: DataFunctionSettings
	(*TaskExecutionSettings)(nil),                  // 33: TaskExecutionSettings
	(*WorkflowExecutionSettings)(nil),              // 34: WorkflowExecutionSettings
	(RegistrationStatus)(0),                        // 35: RegistrationStatus
	(*timestamppb.Timestamp)(nil),                  // 36: google.protobuf.Timestamp
	(TriggerSource)(0),                             // 37: TriggerSource
	(TriggerStatus)(0),                             // 38: TriggerStatus
	(ExecutionStatus)(0),                           // 39: ExecutionStatus
	(*ComputeMetrics)(nil),                         // 40: ComputeMetrics
}
var file_core_proto_depIdxs = []int32{
	32, // 0: DataFunction.settings:type_name -> DataFunctionSettings
	33, // 1: Task.executionSettings:type_name -> TaskExecutionSettings
	5,  // 2: Workflow.edges:type_name -> WorkflowEdge
	34, // 3: Workflow.executionSettings:type_name -> WorkflowExecutionSettings
	35, // 4: RegisterWorkerResponse.status:type_name -> RegistrationStatus
	35, // 5: GetNonceResponse.status:type_name -> RegistrationStatus
	35, // 6: CheckNonceResponse.status:type_name -> RegistrationStatus
	36, // 7: CheckNonceResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 8: RegisterWorkerSnapshotRequest.dataFunctions:type_name -> DataFunction
	4,  // 9: RegisterWorkerSnapshotRequest.tasks:type_name -> Task
	6,  // 10: RegisterWorkerSnapshotRequest.workflows:type_name -> Workflow
	35, // 11: RegisterWorkerSnapshotResponse.status:type_name -> RegistrationStatus
	35, // 12: RegisterServingResponse.status:type_name -> RegistrationStatus
	36, // 13: TriggerWorkflowRequest.logicalDate:type_name -> google.protobuf.Timestamp
	37, // 14: TriggerWorkflowRequest.triggerSource:type_name -> TriggerSource
	38, // 15: TriggerWorkflowResponse.status:type_name -> TriggerStatus
	39, // 16: RegisterDataFunctionCompletionRequest.status:type_name -> ExecutionStatus
	39, // 17: RegisterTaskResultRequest.status:type_name -> ExecutionStatus
	40, // 18: RegisterTaskResultRequest.computeMetrics:type_name -> ComputeMetrics
	36, // 19: ExposeStateRequest.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 20: ExposeStateResponse.tasks:type_name -> Task
	6,  // 21: ExposeStateResponse.workflows:type_name -> Workflow
	3,  // 22: ExposeStateResponse.dataFunctions:type_name -> DataFunction
	28, // 23: QueryTaskRequest.execution_parameter_filters:type_name -> FilterGroup
	28, // 24: QueryTaskRequest.result_filters:type_name -> FilterGroup
	31, // 25: QueryTaskRequest.order_by:type_name -> OrderByStatement
	27, // 26: QueryTaskResponse.results:type_name -> TaskResult
	29, // 27: FilterGroup.filters:type_name -> LeafFilter
	0,  // 28: LeafFilter.comparator:type_name -> Comparator
	30, // 29: LeafFilter.values:type_name -> StringList
	1,  // 30: OrderByStatement.source:type_name -> DataSource
	2,  // 31: OrderByStatement.direction:type_name -> SortDirection
	7,  // 32: Core.RegisterWorker:input_type -> RegisterWorkerRequest
	9,  // 33: Core.GetNonce:input_type -> GetNonceRequest
	11, // 34: Core.CheckNonce:input_type -> CheckNonceRequest
	13, // 35: Core.RegisterWorkerSnapshot:input_type -> RegisterWorkerSnapshotRequest
	15, // 36: Core.RegisterServing:input_type -> RegisterServingRequest
	17, // 37: Core.TriggerWorkflow:input_type -> TriggerWorkflowRequest
	19, // 38: Core.RegisterDataFunctionResult:input_type -> RegisterDataFunctionCompletionRequest
	21, // 39: Core.RegisterTaskResult:input_type -> RegisterTaskResultRequest
	23, // 40: Core.ExposeState:input_type -> ExposeStateRequest
	25, // 41: Core.QueryTaskResult:input_type -> QueryTaskRequest
	8,  // 42: Core.RegisterWorker:output_type -> RegisterWorkerResponse
	10, // 43: Core.GetNonce:output_type -> GetNonceResponse
	12, // 44: Core.CheckNonce:output_type -> CheckNonceResponse
	14, // 45: Core.RegisterWorkerSnapshot:output_type -> RegisterWorkerSnapshotResponse
	16, // 46: Core.RegisterServing:output_type -> RegisterServingResponse
	18, // 47: Core.TriggerWorkflow:output_type -> TriggerWorkflowResponse
	20, // 48: Core.RegisterDataFunctionResult:output_type -> RegisterDataFunctionCompletionResponse
	22, // 49: Core.RegisterTaskResult:output_type -> RegisterTaskResultResponse
	24, // 50: Core.ExposeState:output_type -> ExposeStateResponse
	26, // 51: Core.QueryTaskResult:output_type -> QueryTaskResponse
	42, // [42:52] is the sub-list for method output_type
	32, // [32:42] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_shared_proto_init()
	file_core_proto_msgTypes[14].OneofWrappers = []any{}
	file_core_proto_msgTypes[20].OneofWrappers = []any{}
	file_core_proto_msgTypes[22].OneofWrappers = []any{}
	file_core_proto_msgTypes[23].OneofWrappers = []any{}
	file_core_proto_msgTypes[26].OneofWrappers = []any{
		(*LeafFilter_Value)(nil),
		(*LeafFilter_Values)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		EnumInfos:         file_core_proto_enumTypes,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
