// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: service.proto

package _go

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultType int32

const (
	// placeholder sentinel to make explicit that nothing was provided
	ResultType_NOT_SPECIFIED ResultType = 0
	// the algorithm produces a struct result
	ResultType_STRUCT ResultType = 1
	// the algorithm produces a single value
	ResultType_VALUE ResultType = 2
	// the algorithm produces an array of values
	ResultType_ARRAY ResultType = 3
	// the algorithm does not produce a result
	ResultType_NONE ResultType = 4
)

// Enum value maps for ResultType.
var (
	ResultType_name = map[int32]string{
		0: "NOT_SPECIFIED",
		1: "STRUCT",
		2: "VALUE",
		3: "ARRAY",
		4: "NONE",
	}
	ResultType_value = map[string]int32{
		"NOT_SPECIFIED": 0,
		"STRUCT":        1,
		"VALUE":         2,
		"ARRAY":         3,
		"NONE":          4,
	}
)

func (x ResultType) Enum() *ResultType {
	p := new(ResultType)
	*p = x
	return p
}

func (x ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ResultType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultType.Descriptor instead.
func (ResultType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// ResultStatus indicates the outcome of algorithm execution
type ResultStatus int32

const (
	// Algorithm failed but the error was handled gracefully
	// The system may retry or skip depending on configuration
	ResultStatus_RESULT_STATUS_HANDLED_FAILED ResultStatus = 0
	// Algorithm failed with an unexpected error
	// Requires investigation and may halt dependent processing
	ResultStatus_RESULT_STATUS_UNHANDLED_FAILED ResultStatus = 1
	// Algorithm completed successfully
	// Results are valid and can be used by dependent algorithms
	ResultStatus_RESULT_STATUS_SUCEEDED ResultStatus = 2
)

// Enum value maps for ResultStatus.
var (
	ResultStatus_name = map[int32]string{
		0: "RESULT_STATUS_HANDLED_FAILED",
		1: "RESULT_STATUS_UNHANDLED_FAILED",
		2: "RESULT_STATUS_SUCEEDED",
	}
	ResultStatus_value = map[string]int32{
		"RESULT_STATUS_HANDLED_FAILED":   0,
		"RESULT_STATUS_UNHANDLED_FAILED": 1,
		"RESULT_STATUS_SUCEEDED":         2,
	}
)

func (x ResultStatus) Enum() *ResultStatus {
	p := new(ResultStatus)
	*p = x
	return p
}

func (x ResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (ResultStatus) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x ResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultStatus.Descriptor instead.
func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

// A status enum that captures scenarios regarding a window being emmited
type WindowEmitStatus_StatusEnum int32

const (
	// When triggering has failed
	WindowEmitStatus_TRIGGERING_FAILED WindowEmitStatus_StatusEnum = 0
	// When no algorithms could be found that are triggered by this window
	WindowEmitStatus_NO_TRIGGERED_ALGORITHMS WindowEmitStatus_StatusEnum = 1
	// When processing has successfully been triggered
	WindowEmitStatus_PROCESSING_TRIGGERED WindowEmitStatus_StatusEnum = 2
)

// Enum value maps for WindowEmitStatus_StatusEnum.
var (
	WindowEmitStatus_StatusEnum_name = map[int32]string{
		0: "TRIGGERING_FAILED",
		1: "NO_TRIGGERED_ALGORITHMS",
		2: "PROCESSING_TRIGGERED",
	}
	WindowEmitStatus_StatusEnum_value = map[string]int32{
		"TRIGGERING_FAILED":       0,
		"NO_TRIGGERED_ALGORITHMS": 1,
		"PROCESSING_TRIGGERED":    2,
	}
)

func (x WindowEmitStatus_StatusEnum) Enum() *WindowEmitStatus_StatusEnum {
	p := new(WindowEmitStatus_StatusEnum)
	*p = x
	return p
}

func (x WindowEmitStatus_StatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WindowEmitStatus_StatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[2].Descriptor()
}

func (WindowEmitStatus_StatusEnum) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[2]
}

func (x WindowEmitStatus_StatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WindowEmitStatus_StatusEnum.Descriptor instead.
func (WindowEmitStatus_StatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4, 0}
}

// Overall health status of the processor
type HealthCheckResponse_Status int32

const (
	// Unknown status - should never be used
	HealthCheckResponse_STATUS_UNKNOWN HealthCheckResponse_Status = 0
	// Processor is healthy and ready to accept tasks
	HealthCheckResponse_STATUS_SERVING HealthCheckResponse_Status = 1
	// Processor is starting up or shutting down
	HealthCheckResponse_STATUS_TRANSITIONING HealthCheckResponse_Status = 2
	// Processor is not healthy and cannot accept tasks
	HealthCheckResponse_STATUS_NOT_SERVING HealthCheckResponse_Status = 3
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_SERVING",
		2: "STATUS_TRANSITIONING",
		3: "STATUS_NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"STATUS_UNKNOWN":       0,
		"STATUS_SERVING":       1,
		"STATUS_TRANSITIONING": 2,
		"STATUS_NOT_SERVING":   3,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[3].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[3]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18, 0}
}

// ExposeSettings provides optional settings to the `Expose` procedure
type ExposeSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExcludeProject string                 `protobuf:"bytes,1,opt,name=exclude_project,json=excludeProject,proto3" json:"exclude_project,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExposeSettings) Reset() {
	*x = ExposeSettings{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeSettings) ProtoMessage() {}

func (x *ExposeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeSettings.ProtoReflect.Descriptor instead.
func (*ExposeSettings) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExposeSettings) GetExcludeProject() string {
	if x != nil {
		return x.ExcludeProject
	}
	return ""
}

// Window represents a time-bounded processing context that triggers algorithm execution. Windows are the primary input that start DAG processing flows.
type Window struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time that the window starts - nanoseconds since epoch
	// Required: Must be > Unix epoch (1970-01-01T00:00:00Z)
	TimeFrom *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	// Time that the window ends - nanoseconds since epoch
	// Required: Must be > time_from (validated at message level)
	TimeTo *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	// The canonical name of the window that uniquely identifies it
	WindowTypeName string `protobuf:"bytes,3,opt,name=window_type_name,json=windowTypeName,proto3" json:"window_type_name,omitempty"`
	// The version of the window type
	WindowTypeVersion string `protobuf:"bytes,4,opt,name=window_type_version,json=windowTypeVersion,proto3" json:"window_type_version,omitempty"`
	// A unique identifier that defines where the window came from
	Origin string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	// Additional metadata to attach to this window
	// The schema of this metadata is determined by the combination of
	// window_type_name and window_type_version. Each window type version
	// defines its own required and optional metadata fields, as defined
	// at the time of registration.
	Metadata      *structpb.Struct `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Window) Reset() {
	*x = Window{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Window) ProtoMessage() {}

func (x *Window) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Window.ProtoReflect.Descriptor instead.
func (*Window) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Window) GetTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFrom
	}
	return nil
}

func (x *Window) GetTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeTo
	}
	return nil
}

func (x *Window) GetWindowTypeName() string {
	if x != nil {
		return x.WindowTypeName
	}
	return ""
}

func (x *Window) GetWindowTypeVersion() string {
	if x != nil {
		return x.WindowTypeVersion
	}
	return ""
}

func (x *Window) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Window) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MetadataField describes the metadata that can be carried along with windows
type MetadataField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the metadata field
	// Examples: "AssetID"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the field
	// Examples: "Unique ID of the asset"
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataField) Reset() {
	*x = MetadataField{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataField) ProtoMessage() {}

func (x *MetadataField) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataField.ProtoReflect.Descriptor instead.
func (*MetadataField) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// WindowType defines a category of window that can trigger algorithms.
// Algorithms subscribe to window types to indicate when they should be executed.
type WindowType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the window type - must be globally unique
	// Examples: "daily", "hourly", "market_close", "event_triggered"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the algorithm. Follows basic semver and allows window
	// types to be changed over time, with traceability
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Description of the window
	// E.g. "Emitted every day, at noon"
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Metadata fields that are carried along with this window type
	MetadataFields []*MetadataField `protobuf:"bytes,4,rep,name=metadataFields,proto3" json:"metadataFields,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WindowType) Reset() {
	*x = WindowType{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowType) ProtoMessage() {}

func (x *WindowType) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowType.ProtoReflect.Descriptor instead.
func (*WindowType) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *WindowType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WindowType) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WindowType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WindowType) GetMetadataFields() []*MetadataField {
	if x != nil {
		return x.MetadataFields
	}
	return nil
}

// WindowEmitStatus status message returned after emitting a window
type WindowEmitStatus struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        WindowEmitStatus_StatusEnum `protobuf:"varint,1,opt,name=status,proto3,enum=WindowEmitStatus_StatusEnum" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowEmitStatus) Reset() {
	*x = WindowEmitStatus{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowEmitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowEmitStatus) ProtoMessage() {}

func (x *WindowEmitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowEmitStatus.ProtoReflect.Descriptor instead.
func (*WindowEmitStatus) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *WindowEmitStatus) GetStatus() WindowEmitStatus_StatusEnum {
	if x != nil {
		return x.Status
	}
	return WindowEmitStatus_TRIGGERING_FAILED
}

// AlgorithmDependency defines a requirement that one algorithm has on another's results.
// These dependencies form the edges in the processing DAG.
type AlgorithmDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the required algorithm
	// Must reference an existing algorithm name in the system
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the required algorithm
	// Must follow semantic versioning (e.g., "1.0.0")
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Name of the processor that the algorithm is associated with
	ProcessorName string `protobuf:"bytes,3,opt,name=processor_name,json=processorName,proto3" json:"processor_name,omitempty"`
	// Runtime of the processor that the algorithm is associated with
	ProcessorRuntime string `protobuf:"bytes,4,opt,name=processor_runtime,json=processorRuntime,proto3" json:"processor_runtime,omitempty"`
	// A lookback field that specifies whether this dependency
	// depends on past results of this algorithm
	//
	// Types that are valid to be assigned to Lookback:
	//
	//	*AlgorithmDependency_LookbackNum
	//	*AlgorithmDependency_LookbackTimeDelta
	Lookback      isAlgorithmDependency_Lookback `protobuf_oneof:"lookback"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmDependency) Reset() {
	*x = AlgorithmDependency{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmDependency) ProtoMessage() {}

func (x *AlgorithmDependency) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmDependency.ProtoReflect.Descriptor instead.
func (*AlgorithmDependency) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *AlgorithmDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlgorithmDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AlgorithmDependency) GetProcessorName() string {
	if x != nil {
		return x.ProcessorName
	}
	return ""
}

func (x *AlgorithmDependency) GetProcessorRuntime() string {
	if x != nil {
		return x.ProcessorRuntime
	}
	return ""
}

func (x *AlgorithmDependency) GetLookback() isAlgorithmDependency_Lookback {
	if x != nil {
		return x.Lookback
	}
	return nil
}

func (x *AlgorithmDependency) GetLookbackNum() uint32 {
	if x != nil {
		if x, ok := x.Lookback.(*AlgorithmDependency_LookbackNum); ok {
			return x.LookbackNum
		}
	}
	return 0
}

func (x *AlgorithmDependency) GetLookbackTimeDelta() uint64 {
	if x != nil {
		if x, ok := x.Lookback.(*AlgorithmDependency_LookbackTimeDelta); ok {
			return x.LookbackTimeDelta
		}
	}
	return 0
}

type isAlgorithmDependency_Lookback interface {
	isAlgorithmDependency_Lookback()
}

type AlgorithmDependency_LookbackNum struct {
	// Number of past results to depend on (if at all)
	LookbackNum uint32 `protobuf:"varint,5,opt,name=lookback_num,json=lookbackNum,proto3,oneof"`
}

type AlgorithmDependency_LookbackTimeDelta struct {
	// Timeframe of past results to depend on (in nanoseconds)
	LookbackTimeDelta uint64 `protobuf:"varint,6,opt,name=lookback_time_delta,json=lookbackTimeDelta,proto3,oneof"`
}

func (*AlgorithmDependency_LookbackNum) isAlgorithmDependency_Lookback() {}

func (*AlgorithmDependency_LookbackTimeDelta) isAlgorithmDependency_Lookback() {}

// Algorithm defines a processing unit that can be executed by processors.
// Algorithms form the nodes in the processing DAG and are triggered by specific window types.
type Algorithm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the algorithm - must be globally unique
	// This identifies the algorithm across the system
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the algorithm - must follow semantic versioning
	// Allows for algorithm evolution while maintaining compatibility
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Type of window that triggers this algorithm
	// References a WindowType that will cause this algorithm to execute
	WindowType *WindowType `protobuf:"bytes,3,opt,name=window_type,json=windowType,proto3" json:"window_type,omitempty"`
	// Other algorithms that this algorithm depends on
	// The algorithm won't execute until all dependencies have completed
	// Dependencies must not form cycles - this is statically checked on processor registration
	Dependencies []*AlgorithmDependency `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// The type of result that the algorithm produces. This is specified upfront
	// rather than introspected, to allow for validation
	ResultType ResultType `protobuf:"varint,5,opt,name=result_type,json=resultType,proto3,enum=ResultType" json:"result_type,omitempty"`
	// A freeform description of the algorithm
	Description   string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Algorithm) Reset() {
	*x = Algorithm{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Algorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm) ProtoMessage() {}

func (x *Algorithm) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm.ProtoReflect.Descriptor instead.
func (*Algorithm) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *Algorithm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Algorithm) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Algorithm) GetWindowType() *WindowType {
	if x != nil {
		return x.WindowType
	}
	return nil
}

func (x *Algorithm) GetDependencies() []*AlgorithmDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Algorithm) GetResultType() ResultType {
	if x != nil {
		return x.ResultType
	}
	return ResultType_NOT_SPECIFIED
}

func (x *Algorithm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Container for array of float values
type FloatArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatArray) Reset() {
	*x = FloatArray{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatArray) ProtoMessage() {}

func (x *FloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatArray.ProtoReflect.Descriptor instead.
func (*FloatArray) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *FloatArray) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Result of an algorithm execution
type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the result execution
	Status ResultStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ResultStatus" json:"status,omitempty"`
	// The actual result data - can be either an array of floats or a structured object
	//
	// Types that are valid to be assigned to ResultData:
	//
	//	*Result_SingleValue
	//	*Result_FloatValues
	//	*Result_StructValue
	ResultData isResult_ResultData `protobuf_oneof:"result_data"`
	// Timestamp when the result was produced
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *Result) GetStatus() ResultStatus {
	if x != nil {
		return x.Status
	}
	return ResultStatus_RESULT_STATUS_HANDLED_FAILED
}

func (x *Result) GetResultData() isResult_ResultData {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *Result) GetSingleValue() float32 {
	if x != nil {
		if x, ok := x.ResultData.(*Result_SingleValue); ok {
			return x.SingleValue
		}
	}
	return 0
}

func (x *Result) GetFloatValues() *FloatArray {
	if x != nil {
		if x, ok := x.ResultData.(*Result_FloatValues); ok {
			return x.FloatValues
		}
	}
	return nil
}

func (x *Result) GetStructValue() *structpb.Struct {
	if x != nil {
		if x, ok := x.ResultData.(*Result_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *Result) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type isResult_ResultData interface {
	isResult_ResultData()
}

type Result_SingleValue struct {
	// for single number results
	SingleValue float32 `protobuf:"fixed32,2,opt,name=single_value,json=singleValue,proto3,oneof"`
}

type Result_FloatValues struct {
	// For numeric array results
	FloatValues *FloatArray `protobuf:"bytes,3,opt,name=float_values,json=floatValues,proto3,oneof"`
}

type Result_StructValue struct {
	// For structured data results (JSON-like)
	// Must follow a map<string, value> schema where value corresponds to https://protobuf.dev/reference/protobuf/google.protobuf/#value
	StructValue *structpb.Struct `protobuf:"bytes,4,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*Result_SingleValue) isResult_ResultData() {}

func (*Result_FloatValues) isResult_ResultData() {}

func (*Result_StructValue) isResult_ResultData() {}

// ProcessorRegistration is sent by processors when they start up to announce their capabilities
// to the orchestrator. This establishes a long-lived connection for receiving tasks.
type ProcessorRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name of the runtime
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Language/runtime of the processor
	// Examples: "python3.9", "go1.19", "Rust4.1"
	Runtime string `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// The connection string of the processor
	// e.g. grpc://localhost:5433
	ConnectionStr string `protobuf:"bytes,3,opt,name=connection_str,json=connectionStr,proto3" json:"connection_str,omitempty"`
	// Algorithms this processor can execute
	// The processor must implement all listed algorithms
	SupportedAlgorithms []*Algorithm `protobuf:"bytes,4,rep,name=supported_algorithms,json=supportedAlgorithms,proto3" json:"supported_algorithms,omitempty"`
	// A name that can be attached to a group of processors. Describes the project in which
	// they are defined (typically a single git repository)
	ProjectName   string `protobuf:"bytes,5,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorRegistration) Reset() {
	*x = ProcessorRegistration{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorRegistration) ProtoMessage() {}

func (x *ProcessorRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorRegistration.ProtoReflect.Descriptor instead.
func (*ProcessorRegistration) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessorRegistration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessorRegistration) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ProcessorRegistration) GetConnectionStr() string {
	if x != nil {
		return x.ConnectionStr
	}
	return ""
}

func (x *ProcessorRegistration) GetSupportedAlgorithms() []*Algorithm {
	if x != nil {
		return x.SupportedAlgorithms
	}
	return nil
}

func (x *ProcessorRegistration) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

// The result of a dependency
type AlgorithmDependencyResultRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The result
	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// The window that triggered the result
	Window        *Window `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmDependencyResultRow) Reset() {
	*x = AlgorithmDependencyResultRow{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmDependencyResultRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmDependencyResultRow) ProtoMessage() {}

func (x *AlgorithmDependencyResultRow) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmDependencyResultRow.ProtoReflect.Descriptor instead.
func (*AlgorithmDependencyResultRow) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *AlgorithmDependencyResultRow) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AlgorithmDependencyResultRow) GetWindow() *Window {
	if x != nil {
		return x.Window
	}
	return nil
}

// A sequence of results for an algorithm dependency
type AlgorithmDependencyResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Algorithm
	Algorithm *Algorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// The result
	Result        []*AlgorithmDependencyResultRow `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmDependencyResult) Reset() {
	*x = AlgorithmDependencyResult{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmDependencyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmDependencyResult) ProtoMessage() {}

func (x *AlgorithmDependencyResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmDependencyResult.ProtoReflect.Descriptor instead.
func (*AlgorithmDependencyResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *AlgorithmDependencyResult) GetAlgorithm() *Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *AlgorithmDependencyResult) GetResult() []*AlgorithmDependencyResultRow {
	if x != nil {
		return x.Result
	}
	return nil
}

// The algorithm execution packet
type ExecuteAlgorithm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The algorithm to execute
	Algorithm *Algorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// The results of a dependent algorithm
	Dependencies  []*AlgorithmDependencyResult `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteAlgorithm) Reset() {
	*x = ExecuteAlgorithm{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAlgorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAlgorithm) ProtoMessage() {}

func (x *ExecuteAlgorithm) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAlgorithm.ProtoReflect.Descriptor instead.
func (*ExecuteAlgorithm) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteAlgorithm) GetAlgorithm() *Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *ExecuteAlgorithm) GetDependencies() []*AlgorithmDependencyResult {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// ExecutionRequest provides a statement of processing as requested
// by Orca core.
type ExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exec_id
	ExecId string `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// The window that triggered the algorithm
	Window *Window `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	// Results from dependant algorithms
	//
	// Deprecated: Marked as deprecated in service.proto.
	AlgorithmResults []*AlgorithmResult `protobuf:"bytes,3,rep,name=algorithm_results,json=algorithmResults,proto3" json:"algorithm_results,omitempty"`
	// The algorithms to execute
	//
	// Deprecated: Marked as deprecated in service.proto.
	Algorithms          []*Algorithm        `protobuf:"bytes,4,rep,name=algorithms,proto3" json:"algorithms,omitempty"` // FIXME:
	AlgorithmExecutions []*ExecuteAlgorithm `protobuf:"bytes,5,rep,name=algorithm_executions,json=algorithmExecutions,proto3" json:"algorithm_executions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *ExecutionRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecutionRequest) GetWindow() *Window {
	if x != nil {
		return x.Window
	}
	return nil
}

// Deprecated: Marked as deprecated in service.proto.
func (x *ExecutionRequest) GetAlgorithmResults() []*AlgorithmResult {
	if x != nil {
		return x.AlgorithmResults
	}
	return nil
}

// Deprecated: Marked as deprecated in service.proto.
func (x *ExecutionRequest) GetAlgorithms() []*Algorithm {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *ExecutionRequest) GetAlgorithmExecutions() []*ExecuteAlgorithm {
	if x != nil {
		return x.AlgorithmExecutions
	}
	return nil
}

type ExecutionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exec ID
	ExecId string `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// The algorithn result
	AlgorithmResult *AlgorithmResult `protobuf:"bytes,3,opt,name=algorithm_result,json=algorithmResult,proto3" json:"algorithm_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *ExecutionResult) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecutionResult) GetAlgorithmResult() *AlgorithmResult {
	if x != nil {
		return x.AlgorithmResult
	}
	return nil
}

// AlgorithmWindowResult Packaged algorithm and result to a window
type AlgorithmResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     *Algorithm             `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Window        *Window                `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmResult) Reset() {
	*x = AlgorithmResult{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmResult) ProtoMessage() {}

func (x *AlgorithmResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmResult.ProtoReflect.Descriptor instead.
func (*AlgorithmResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *AlgorithmResult) GetAlgorithm() *Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *AlgorithmResult) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AlgorithmResult) GetWindow() *Window {
	if x != nil {
		return x.Window
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *Status) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthCheckRequest is sent to processors to verify they are functioning
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the request in unix epoch milliseconds
	// Used to measure response latency
	Timestamp     int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheckRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthCheckResponse indicates the health status of a processor
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current health status
	Status HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=HealthCheckResponse_Status" json:"status,omitempty"`
	// Optional message providing more detail about the health status
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// System metrics about the processor
	Metrics       *ProcessorMetrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_STATUS_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetMetrics() *ProcessorMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// ProcessorMetrics provides runtime information about a processor
type ProcessorMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of algorithms currently being executed
	ActiveTasks int32 `protobuf:"varint,1,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	// Memory usage in bytes
	MemoryBytes int64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// CPU usage percentage (0-100)
	CpuPercent float32 `protobuf:"fixed32,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// Time since processor started in seconds
	UptimeSeconds int64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorMetrics) Reset() {
	*x = ProcessorMetrics{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorMetrics) ProtoMessage() {}

func (x *ProcessorMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorMetrics.ProtoReflect.Descriptor instead.
func (*ProcessorMetrics) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *ProcessorMetrics) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *ProcessorMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProcessorMetrics) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessorMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// InternalState provides a complete snapshot of Orca's registry.
// This is used by clients to "clone" the remote state into local code stubs.
type InternalState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global list of all registered processors and their metadata
	Processors    []*ProcessorRegistration `protobuf:"bytes,1,rep,name=processors,proto3" json:"processors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalState) Reset() {
	*x = InternalState{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalState) ProtoMessage() {}

func (x *InternalState) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalState.ProtoReflect.Descriptor instead.
func (*InternalState) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *InternalState) GetProcessors() []*ProcessorRegistration {
	if x != nil {
		return x.Processors
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15vendor/validate.proto\"9\n" +
	"\x0eExposeSettings\x12'\n" +
	"\x0fexclude_project\x18\x01 \x01(\tR\x0eexcludeProject\"\xbf\x03\n" +
	"\x06Window\x12D\n" +
	"\ttime_from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\v\xbaH\b\xc8\x01\x01\xb2\x01\x02*\x00R\btimeFrom\x12@\n" +
	"\atime_to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\v\xbaH\b\xc8\x01\x01\xb2\x01\x02*\x00R\x06timeTo\x124\n" +
	"\x10window_type_name\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x0ewindowTypeName\x12:\n" +
	"\x13window_type_version\x18\x04 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x11windowTypeVersion\x12\"\n" +
	"\x06origin\x18\x05 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06origin\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata:b\xbaH_\x1a]\n" +
	"\x14window.time_ordering\x12&time_to must be greater than time_from\x1a\x1dthis.time_to > this.time_from\"U\n" +
	"\rMetadataField\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12(\n" +
	"\vdescription\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\vdescription\"\xac\x01\n" +
	"\n" +
	"WindowType\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\aversion\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aversion\x12(\n" +
	"\vdescription\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\vdescription\x126\n" +
	"\x0emetadataFields\x18\x04 \x03(\v2\x0e.MetadataFieldR\x0emetadataFields\"\xac\x01\n" +
	"\x10WindowEmitStatus\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.WindowEmitStatus.StatusEnumB\x06\xbaH\x03\xc8\x01\x01R\x06status\"Z\n" +
	"\n" +
	"StatusEnum\x12\x15\n" +
	"\x11TRIGGERING_FAILED\x10\x00\x12\x1b\n" +
	"\x17NO_TRIGGERED_ALGORITHMS\x10\x01\x12\x18\n" +
	"\x14PROCESSING_TRIGGERED\x10\x02\"\xa1\x02\n" +
	"\x13AlgorithmDependency\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\aversion\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aversion\x12-\n" +
	"\x0eprocessor_name\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rprocessorName\x123\n" +
	"\x11processor_runtime\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x10processorRuntime\x12#\n" +
	"\flookback_num\x18\x05 \x01(\rH\x00R\vlookbackNum\x120\n" +
	"\x13lookback_time_delta\x18\x06 \x01(\x04H\x00R\x11lookbackTimeDeltaB\x11\n" +
	"\blookback\x12\x05\xbaH\x02\b\x00\"\x9e\x02\n" +
	"\tAlgorithm\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\aversion\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aversion\x124\n" +
	"\vwindow_type\x18\x03 \x01(\v2\v.WindowTypeB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"windowType\x128\n" +
	"\fdependencies\x18\x04 \x03(\v2\x14.AlgorithmDependencyR\fdependencies\x124\n" +
	"\vresult_type\x18\x05 \x01(\x0e2\v.ResultTypeB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"resultType\x12-\n" +
	"\vdescription\x18\x06 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x18\xe8\aR\vdescription\"$\n" +
	"\n" +
	"FloatArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\x81\x02\n" +
	"\x06Result\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.ResultStatusB\x06\xbaH\x03\xc8\x01\x01R\x06status\x12#\n" +
	"\fsingle_value\x18\x02 \x01(\x02H\x00R\vsingleValue\x120\n" +
	"\ffloat_values\x18\x03 \x01(\v2\v.FloatArrayH\x00R\vfloatValues\x12<\n" +
	"\fstruct_value\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x00R\vstructValue\x12$\n" +
	"\ttimestamp\x18\x05 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\ttimestampB\r\n" +
	"\vresult_data\"\xee\x01\n" +
	"\x15ProcessorRegistration\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\aruntime\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aruntime\x12-\n" +
	"\x0econnection_str\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rconnectionStr\x12E\n" +
	"\x14supported_algorithms\x18\x04 \x03(\v2\n" +
	".AlgorithmB\x06\xbaH\x03\xc8\x01\x01R\x13supportedAlgorithms\x12!\n" +
	"\fproject_name\x18\x05 \x01(\tR\vprojectName\"p\n" +
	"\x1cAlgorithmDependencyResultRow\x12'\n" +
	"\x06result\x18\x01 \x01(\v2\a.ResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\x12'\n" +
	"\x06window\x18\x02 \x01(\v2\a.WindowB\x06\xbaH\x03\xc8\x01\x01R\x06window\"\x8c\x01\n" +
	"\x19AlgorithmDependencyResult\x120\n" +
	"\talgorithm\x18\x01 \x01(\v2\n" +
	".AlgorithmB\x06\xbaH\x03\xc8\x01\x01R\talgorithm\x12=\n" +
	"\x06result\x18\x02 \x03(\v2\x1d.AlgorithmDependencyResultRowB\x06\xbaH\x03\xc8\x01\x01R\x06result\"\x84\x01\n" +
	"\x10ExecuteAlgorithm\x120\n" +
	"\talgorithm\x18\x01 \x01(\v2\n" +
	".AlgorithmB\x06\xbaH\x03\xc8\x01\x01R\talgorithm\x12>\n" +
	"\fdependencies\x18\x02 \x03(\v2\x1a.AlgorithmDependencyResultR\fdependencies\"\x9d\x02\n" +
	"\x10ExecutionRequest\x12\x1f\n" +
	"\aexec_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06execId\x12'\n" +
	"\x06window\x18\x02 \x01(\v2\a.WindowB\x06\xbaH\x03\xc8\x01\x01R\x06window\x12A\n" +
	"\x11algorithm_results\x18\x03 \x03(\v2\x10.AlgorithmResultB\x02\x18\x01R\x10algorithmResults\x12.\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\v2\n" +
	".AlgorithmB\x02\x18\x01R\n" +
	"algorithms\x12L\n" +
	"\x14algorithm_executions\x18\x05 \x03(\v2\x11.ExecuteAlgorithmB\x06\xbaH\x03\xc8\x01\x01R\x13algorithmExecutions\"w\n" +
	"\x0fExecutionResult\x12\x1f\n" +
	"\aexec_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06execId\x12C\n" +
	"\x10algorithm_result\x18\x03 \x01(\v2\x10.AlgorithmResultB\x06\xbaH\x03\xc8\x01\x01R\x0falgorithmResult\"\x95\x01\n" +
	"\x0fAlgorithmResult\x120\n" +
	"\talgorithm\x18\x01 \x01(\v2\n" +
	".AlgorithmB\x06\xbaH\x03\xc8\x01\x01R\talgorithm\x12'\n" +
	"\x06result\x18\x02 \x01(\v2\a.ResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\x12'\n" +
	"\x06window\x18\x03 \x01(\v2\a.WindowB\x06\xbaH\x03\xc8\x01\x01R\x06window\">\n" +
	"\x06Status\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x12HealthCheckRequest\x12$\n" +
	"\ttimestamp\x18\x01 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\ttimestamp\"\xfd\x01\n" +
	"\x13HealthCheckResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.HealthCheckResponse.StatusB\x06\xbaH\x03\xc8\x01\x01R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\ametrics\x18\x03 \x01(\v2\x11.ProcessorMetricsR\ametrics\"b\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SERVING\x10\x01\x12\x18\n" +
	"\x14STATUS_TRANSITIONING\x10\x02\x12\x16\n" +
	"\x12STATUS_NOT_SERVING\x10\x03\"\xa0\x01\n" +
	"\x10ProcessorMetrics\x12!\n" +
	"\factive_tasks\x18\x01 \x01(\x05R\vactiveTasks\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x02R\n" +
	"cpuPercent\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"G\n" +
	"\rInternalState\x126\n" +
	"\n" +
	"processors\x18\x01 \x03(\v2\x16.ProcessorRegistrationR\n" +
	"processors*K\n" +
	"\n" +
	"ResultType\x12\x11\n" +
	"\rNOT_SPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STRUCT\x10\x01\x12\t\n" +
	"\x05VALUE\x10\x02\x12\t\n" +
	"\x05ARRAY\x10\x03\x12\b\n" +
	"\x04NONE\x10\x04*p\n" +
	"\fResultStatus\x12 \n" +
	"\x1cRESULT_STATUS_HANDLED_FAILED\x10\x00\x12\"\n" +
	"\x1eRESULT_STATUS_UNHANDLED_FAILED\x10\x01\x12\x1a\n" +
	"\x16RESULT_STATUS_SUCEEDED\x10\x022\x95\x01\n" +
	"\bOrcaCore\x124\n" +
	"\x11RegisterProcessor\x12\x16.ProcessorRegistration\x1a\a.Status\x12(\n" +
	"\n" +
	"EmitWindow\x12\a.Window\x1a\x11.WindowEmitStatus\x12)\n" +
	"\x06Expose\x12\x0f.ExposeSettings\x1a\x0e.InternalState2\x82\x01\n" +
	"\rOrcaProcessor\x127\n" +
	"\x0eExecuteDagPart\x12\x11.ExecutionRequest\x1a\x10.ExecutionResult0\x01\x128\n" +
	"\vHealthCheck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponseB'Z%github.com/orca-telemetry/contract/gob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_service_proto_goTypes = []any{
	(ResultType)(0),                      // 0: ResultType
	(ResultStatus)(0),                    // 1: ResultStatus
	(WindowEmitStatus_StatusEnum)(0),     // 2: WindowEmitStatus.StatusEnum
	(HealthCheckResponse_Status)(0),      // 3: HealthCheckResponse.Status
	(*ExposeSettings)(nil),               // 4: ExposeSettings
	(*Window)(nil),                       // 5: Window
	(*MetadataField)(nil),                // 6: MetadataField
	(*WindowType)(nil),                   // 7: WindowType
	(*WindowEmitStatus)(nil),             // 8: WindowEmitStatus
	(*AlgorithmDependency)(nil),          // 9: AlgorithmDependency
	(*Algorithm)(nil),                    // 10: Algorithm
	(*FloatArray)(nil),                   // 11: FloatArray
	(*Result)(nil),                       // 12: Result
	(*ProcessorRegistration)(nil),        // 13: ProcessorRegistration
	(*AlgorithmDependencyResultRow)(nil), // 14: AlgorithmDependencyResultRow
	(*AlgorithmDependencyResult)(nil),    // 15: AlgorithmDependencyResult
	(*ExecuteAlgorithm)(nil),             // 16: ExecuteAlgorithm
	(*ExecutionRequest)(nil),             // 17: ExecutionRequest
	(*ExecutionResult)(nil),              // 18: ExecutionResult
	(*AlgorithmResult)(nil),              // 19: AlgorithmResult
	(*Status)(nil),                       // 20: Status
	(*HealthCheckRequest)(nil),           // 21: HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 22: HealthCheckResponse
	(*ProcessorMetrics)(nil),             // 23: ProcessorMetrics
	(*InternalState)(nil),                // 24: InternalState
	(*timestamppb.Timestamp)(nil),        // 25: google.protobuf.Timestamp
	(*structpb.Struct)(nil),              // 26: google.protobuf.Struct
}
var file_service_proto_depIdxs = []int32{
	25, // 0: Window.time_from:type_name -> google.protobuf.Timestamp
	25, // 1: Window.time_to:type_name -> google.protobuf.Timestamp
	26, // 2: Window.metadata:type_name -> google.protobuf.Struct
	6,  // 3: WindowType.metadataFields:type_name -> MetadataField
	2,  // 4: WindowEmitStatus.status:type_name -> WindowEmitStatus.StatusEnum
	7,  // 5: Algorithm.window_type:type_name -> WindowType
	9,  // 6: Algorithm.dependencies:type_name -> AlgorithmDependency
	0,  // 7: Algorithm.result_type:type_name -> ResultType
	1,  // 8: Result.status:type_name -> ResultStatus
	11, // 9: Result.float_values:type_name -> FloatArray
	26, // 10: Result.struct_value:type_name -> google.protobuf.Struct
	10, // 11: ProcessorRegistration.supported_algorithms:type_name -> Algorithm
	12, // 12: AlgorithmDependencyResultRow.result:type_name -> Result
	5,  // 13: AlgorithmDependencyResultRow.window:type_name -> Window
	10, // 14: AlgorithmDependencyResult.algorithm:type_name -> Algorithm
	14, // 15: AlgorithmDependencyResult.result:type_name -> AlgorithmDependencyResultRow
	10, // 16: ExecuteAlgorithm.algorithm:type_name -> Algorithm
	15, // 17: ExecuteAlgorithm.dependencies:type_name -> AlgorithmDependencyResult
	5,  // 18: ExecutionRequest.window:type_name -> Window
	19, // 19: ExecutionRequest.algorithm_results:type_name -> AlgorithmResult
	10, // 20: ExecutionRequest.algorithms:type_name -> Algorithm
	16, // 21: ExecutionRequest.algorithm_executions:type_name -> ExecuteAlgorithm
	19, // 22: ExecutionResult.algorithm_result:type_name -> AlgorithmResult
	10, // 23: AlgorithmResult.algorithm:type_name -> Algorithm
	12, // 24: AlgorithmResult.result:type_name -> Result
	5,  // 25: AlgorithmResult.window:type_name -> Window
	3,  // 26: HealthCheckResponse.status:type_name -> HealthCheckResponse.Status
	23, // 27: HealthCheckResponse.metrics:type_name -> ProcessorMetrics
	13, // 28: InternalState.processors:type_name -> ProcessorRegistration
	13, // 29: OrcaCore.RegisterProcessor:input_type -> ProcessorRegistration
	5,  // 30: OrcaCore.EmitWindow:input_type -> Window
	4,  // 31: OrcaCore.Expose:input_type -> ExposeSettings
	17, // 32: OrcaProcessor.ExecuteDagPart:input_type -> ExecutionRequest
	21, // 33: OrcaProcessor.HealthCheck:input_type -> HealthCheckRequest
	20, // 34: OrcaCore.RegisterProcessor:output_type -> Status
	8,  // 35: OrcaCore.EmitWindow:output_type -> WindowEmitStatus
	24, // 36: OrcaCore.Expose:output_type -> InternalState
	18, // 37: OrcaProcessor.ExecuteDagPart:output_type -> ExecutionResult
	22, // 38: OrcaProcessor.HealthCheck:output_type -> HealthCheckResponse
	34, // [34:39] is the sub-list for method output_type
	29, // [29:34] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[5].OneofWrappers = []any{
		(*AlgorithmDependency_LookbackNum)(nil),
		(*AlgorithmDependency_LookbackTimeDelta)(nil),
	}
	file_service_proto_msgTypes[8].OneofWrappers = []any{
		(*Result_SingleValue)(nil),
		(*Result_FloatValues)(nil),
		(*Result_StructValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
