// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: shared.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TriggerSource denotes the origin of a workflow trigger event.
type TriggerSource int32

const (
	TriggerSource_TRIGGER_SOURCE_UNSPECIFIED TriggerSource = 0
	TriggerSource_TRIGGER_SOURCE_CRON        TriggerSource = 1
	TriggerSource_TRIGGER_SOURCE_WEBHOOK     TriggerSource = 2
	TriggerSource_TRIGGER_SOURCE_UI          TriggerSource = 3
	TriggerSource_TRIGGER_SOURCE_CLI         TriggerSource = 4
)

// Enum value maps for TriggerSource.
var (
	TriggerSource_name = map[int32]string{
		0: "TRIGGER_SOURCE_UNSPECIFIED",
		1: "TRIGGER_SOURCE_CRON",
		2: "TRIGGER_SOURCE_WEBHOOK",
		3: "TRIGGER_SOURCE_UI",
		4: "TRIGGER_SOURCE_CLI",
	}
	TriggerSource_value = map[string]int32{
		"TRIGGER_SOURCE_UNSPECIFIED": 0,
		"TRIGGER_SOURCE_CRON":        1,
		"TRIGGER_SOURCE_WEBHOOK":     2,
		"TRIGGER_SOURCE_UI":          3,
		"TRIGGER_SOURCE_CLI":         4,
	}
)

func (x TriggerSource) Enum() *TriggerSource {
	p := new(TriggerSource)
	*p = x
	return p
}

func (x TriggerSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerSource) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[0].Descriptor()
}

func (TriggerSource) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[0]
}

func (x TriggerSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerSource.Descriptor instead.
func (TriggerSource) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{0}
}

// TriggerStatus is the result of a workflow trigger RPC.
type TriggerStatus int32

const (
	TriggerStatus_TRIGGER_STATUS_UNSPECIFIED TriggerStatus = 0
	TriggerStatus_TRIGGER_STATUS_ACCEPTED    TriggerStatus = 1
	TriggerStatus_TRIGGER_STATUS_REJECTED    TriggerStatus = 2
)

// Enum value maps for TriggerStatus.
var (
	TriggerStatus_name = map[int32]string{
		0: "TRIGGER_STATUS_UNSPECIFIED",
		1: "TRIGGER_STATUS_ACCEPTED",
		2: "TRIGGER_STATUS_REJECTED",
	}
	TriggerStatus_value = map[string]int32{
		"TRIGGER_STATUS_UNSPECIFIED": 0,
		"TRIGGER_STATUS_ACCEPTED":    1,
		"TRIGGER_STATUS_REJECTED":    2,
	}
)

func (x TriggerStatus) Enum() *TriggerStatus {
	p := new(TriggerStatus)
	*p = x
	return p
}

func (x TriggerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[1].Descriptor()
}

func (TriggerStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[1]
}

func (x TriggerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerStatus.Descriptor instead.
func (TriggerStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{1}
}

// ExecutionStatus is the result of a task or data function execution.
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_SUCCESSFUL  ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 2
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_SUCCESSFUL",
		2: "EXECUTION_STATUS_FAILED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_SUCCESSFUL":  1,
		"EXECUTION_STATUS_FAILED":      2,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[2].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[2]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{2}
}

// BackoffStrategy defines the retry backoff behaviour for a task.
type BackoffStrategy int32

const (
	BackoffStrategy_BACKOFF_STRATEGY_UNSPECIFIED BackoffStrategy = 0
	BackoffStrategy_BACKOFF_STRATEGY_LINEAR      BackoffStrategy = 1
	BackoffStrategy_BACKOFF_STRATEGY_EXPONENTIAL BackoffStrategy = 2
)

// Enum value maps for BackoffStrategy.
var (
	BackoffStrategy_name = map[int32]string{
		0: "BACKOFF_STRATEGY_UNSPECIFIED",
		1: "BACKOFF_STRATEGY_LINEAR",
		2: "BACKOFF_STRATEGY_EXPONENTIAL",
	}
	BackoffStrategy_value = map[string]int32{
		"BACKOFF_STRATEGY_UNSPECIFIED": 0,
		"BACKOFF_STRATEGY_LINEAR":      1,
		"BACKOFF_STRATEGY_EXPONENTIAL": 2,
	}
)

func (x BackoffStrategy) Enum() *BackoffStrategy {
	p := new(BackoffStrategy)
	*p = x
	return p
}

func (x BackoffStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackoffStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[3].Descriptor()
}

func (BackoffStrategy) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[3]
}

func (x BackoffStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackoffStrategy.Descriptor instead.
func (BackoffStrategy) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{3}
}

// DataFunctionSettings holds configuration that governs the lifecycle of
// data produced by a data function.
type DataFunctionSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TTL controls how long produced data is retained.
	// 0 = clean up immediately after DAG execution of all dependent tasks completes.
	// >0 = retention duration in seconds.
	Ttl int32 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Timeout is the maximum duration (in seconds) allowed for the data
	// function's full lifecycle.
	Timeout       int32 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFunctionSettings) Reset() {
	*x = DataFunctionSettings{}
	mi := &file_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFunctionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFunctionSettings) ProtoMessage() {}

func (x *DataFunctionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFunctionSettings.ProtoReflect.Descriptor instead.
func (*DataFunctionSettings) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{0}
}

func (x *DataFunctionSettings) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DataFunctionSettings) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// TaskExecutionSettings governs how a task is executed and retried.
type TaskExecutionSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ExecutionTimeout is the maximum duration (in seconds) allowed for a
	// single task execution attempt.
	ExecutionTimeout int32 `protobuf:"varint,1,opt,name=executionTimeout,proto3" json:"executionTimeout,omitempty"`
	// RetryCount is the number of times the task should be retried on failure.
	RetryCount int32 `protobuf:"varint,2,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	// BackoffStrategy defines whether retries use linear or exponential backoff.
	BackoffStrategy BackoffStrategy `protobuf:"varint,3,opt,name=backoffStrategy,proto3,enum=BackoffStrategy" json:"backoffStrategy,omitempty"`
	// Deadline is an SLA value in seconds. If execution exceeds this deadline,
	// an alert is raised against this task's execution status.
	Deadline      int32 `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecutionSettings) Reset() {
	*x = TaskExecutionSettings{}
	mi := &file_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecutionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecutionSettings) ProtoMessage() {}

func (x *TaskExecutionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecutionSettings.ProtoReflect.Descriptor instead.
func (*TaskExecutionSettings) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExecutionSettings) GetExecutionTimeout() int32 {
	if x != nil {
		return x.ExecutionTimeout
	}
	return 0
}

func (x *TaskExecutionSettings) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskExecutionSettings) GetBackoffStrategy() BackoffStrategy {
	if x != nil {
		return x.BackoffStrategy
	}
	return BackoffStrategy_BACKOFF_STRATEGY_UNSPECIFIED
}

func (x *TaskExecutionSettings) GetDeadline() int32 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

// RequiredPastResult describes a prior task result that must be available
// before the owning task can execute.
type RequiredPastResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TaskName is the name of the task whose prior result is required.
	TaskName string `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	// ExecutionParams is the marshalled JSON of the execution parameters
	// used when the referenced workflow was triggered.
	ExecutionParams string `protobuf:"bytes,2,opt,name=executionParams,proto3" json:"executionParams,omitempty"`
	// TaskResult is the expected result value of the referenced task execution.
	TaskResult    string `protobuf:"bytes,3,opt,name=taskResult,proto3" json:"taskResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredPastResult) Reset() {
	*x = RequiredPastResult{}
	mi := &file_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredPastResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredPastResult) ProtoMessage() {}

func (x *RequiredPastResult) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredPastResult.ProtoReflect.Descriptor instead.
func (*RequiredPastResult) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{2}
}

func (x *RequiredPastResult) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *RequiredPastResult) GetExecutionParams() string {
	if x != nil {
		return x.ExecutionParams
	}
	return ""
}

func (x *RequiredPastResult) GetTaskResult() string {
	if x != nil {
		return x.TaskResult
	}
	return ""
}

// WorkflowExecutionSettings defines pipeline-level concurrency and
// prioritisation configuration.
type WorkflowExecutionSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PriorityQueue lists tasks that should be prioritised over others
	// during parallel execution.
	PriorityQueue []string `protobuf:"bytes,1,rep,name=priorityQueue,proto3" json:"priorityQueue,omitempty"`
	// ConcurrencyLimit caps the number of tasks that may execute in
	// parallel at any point in time.
	ConcurrencyLimit int32 `protobuf:"varint,2,opt,name=concurrencyLimit,proto3" json:"concurrencyLimit,omitempty"`
	// HaltOnFailure instructs the orchestrator to stop parallel task execution
	// if any task encounters a failure.
	HaltOnFailure bool `protobuf:"varint,3,opt,name=haltOnFailure,proto3" json:"haltOnFailure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecutionSettings) Reset() {
	*x = WorkflowExecutionSettings{}
	mi := &file_shared_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionSettings) ProtoMessage() {}

func (x *WorkflowExecutionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionSettings.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionSettings) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowExecutionSettings) GetPriorityQueue() []string {
	if x != nil {
		return x.PriorityQueue
	}
	return nil
}

func (x *WorkflowExecutionSettings) GetConcurrencyLimit() int32 {
	if x != nil {
		return x.ConcurrencyLimit
	}
	return 0
}

func (x *WorkflowExecutionSettings) GetHaltOnFailure() bool {
	if x != nil {
		return x.HaltOnFailure
	}
	return false
}

// ComputeMetrics captures resource consumption for a single task execution.
type ComputeMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CpuSeconds is the total CPU time consumed, measured in CPU-seconds.
	CpuSeconds float64 `protobuf:"fixed64,1,opt,name=cpuSeconds,proto3" json:"cpuSeconds,omitempty"`
	// MemoryGiBSeconds is the total memory consumed, measured in GiB-seconds.
	MemoryGiBSeconds float64 `protobuf:"fixed64,2,opt,name=memoryGiBSeconds,proto3" json:"memoryGiBSeconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComputeMetrics) Reset() {
	*x = ComputeMetrics{}
	mi := &file_shared_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeMetrics) ProtoMessage() {}

func (x *ComputeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeMetrics.ProtoReflect.Descriptor instead.
func (*ComputeMetrics) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{4}
}

func (x *ComputeMetrics) GetCpuSeconds() float64 {
	if x != nil {
		return x.CpuSeconds
	}
	return 0
}

func (x *ComputeMetrics) GetMemoryGiBSeconds() float64 {
	if x != nil {
		return x.MemoryGiBSeconds
	}
	return 0
}

var File_shared_proto protoreflect.FileDescriptor

const file_shared_proto_rawDesc = "" +
	"\n" +
	"\fshared.proto\"B\n" +
	"\x14DataFunctionSettings\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x05R\x03ttl\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"\xbb\x01\n" +
	"\x15TaskExecutionSettings\x12*\n" +
	"\x10executionTimeout\x18\x01 \x01(\x05R\x10executionTimeout\x12\x1e\n" +
	"\n" +
	"retryCount\x18\x02 \x01(\x05R\n" +
	"retryCount\x12:\n" +
	"\x0fbackoffStrategy\x18\x03 \x01(\x0e2\x10.BackoffStrategyR\x0fbackoffStrategy\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\x05R\bdeadline\"z\n" +
	"\x12RequiredPastResult\x12\x1a\n" +
	"\btaskName\x18\x01 \x01(\tR\btaskName\x12(\n" +
	"\x0fexecutionParams\x18\x02 \x01(\tR\x0fexecutionParams\x12\x1e\n" +
	"\n" +
	"taskResult\x18\x03 \x01(\tR\n" +
	"taskResult\"\x93\x01\n" +
	"\x19WorkflowExecutionSettings\x12$\n" +
	"\rpriorityQueue\x18\x01 \x03(\tR\rpriorityQueue\x12*\n" +
	"\x10concurrencyLimit\x18\x02 \x01(\x05R\x10concurrencyLimit\x12$\n" +
	"\rhaltOnFailure\x18\x03 \x01(\bR\rhaltOnFailure\"\\\n" +
	"\x0eComputeMetrics\x12\x1e\n" +
	"\n" +
	"cpuSeconds\x18\x01 \x01(\x01R\n" +
	"cpuSeconds\x12*\n" +
	"\x10memoryGiBSeconds\x18\x02 \x01(\x01R\x10memoryGiBSeconds*\x93\x01\n" +
	"\rTriggerSource\x12\x1e\n" +
	"\x1aTRIGGER_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRIGGER_SOURCE_CRON\x10\x01\x12\x1a\n" +
	"\x16TRIGGER_SOURCE_WEBHOOK\x10\x02\x12\x15\n" +
	"\x11TRIGGER_SOURCE_UI\x10\x03\x12\x16\n" +
	"\x12TRIGGER_SOURCE_CLI\x10\x04*i\n" +
	"\rTriggerStatus\x12\x1e\n" +
	"\x1aTRIGGER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRIGGER_STATUS_ACCEPTED\x10\x01\x12\x1b\n" +
	"\x17TRIGGER_STATUS_REJECTED\x10\x02*q\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bEXECUTION_STATUS_SUCCESSFUL\x10\x01\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x02*r\n" +
	"\x0fBackoffStrategy\x12 \n" +
	"\x1cBACKOFF_STRATEGY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BACKOFF_STRATEGY_LINEAR\x10\x01\x12 \n" +
	"\x1cBACKOFF_STRATEGY_EXPONENTIAL\x10\x02B*Z(github.com/orca-telemetry/contract/go/v2b\x06proto3"

var (
	file_shared_proto_rawDescOnce sync.Once
	file_shared_proto_rawDescData []byte
)

func file_shared_proto_rawDescGZIP() []byte {
	file_shared_proto_rawDescOnce.Do(func() {
		file_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_rawDesc), len(file_shared_proto_rawDesc)))
	})
	return file_shared_proto_rawDescData
}

var file_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_proto_goTypes = []any{
	(TriggerSource)(0),                // 0: TriggerSource
	(TriggerStatus)(0),                // 1: TriggerStatus
	(ExecutionStatus)(0),              // 2: ExecutionStatus
	(BackoffStrategy)(0),              // 3: BackoffStrategy
	(*DataFunctionSettings)(nil),      // 4: DataFunctionSettings
	(*TaskExecutionSettings)(nil),     // 5: TaskExecutionSettings
	(*RequiredPastResult)(nil),        // 6: RequiredPastResult
	(*WorkflowExecutionSettings)(nil), // 7: WorkflowExecutionSettings
	(*ComputeMetrics)(nil),            // 8: ComputeMetrics
}
var file_shared_proto_depIdxs = []int32{
	3, // 0: TaskExecutionSettings.backoffStrategy:type_name -> BackoffStrategy
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_init() }
func file_shared_proto_init() {
	if File_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_rawDesc), len(file_shared_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_goTypes,
		DependencyIndexes: file_shared_proto_depIdxs,
		EnumInfos:         file_shared_proto_enumTypes,
		MessageInfos:      file_shared_proto_msgTypes,
	}.Build()
	File_shared_proto = out.File
	file_shared_proto_goTypes = nil
	file_shared_proto_depIdxs = nil
}
