// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: worker.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteDataFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ExecutionParameters is a marshalled JSON struct conforming to the data
	// function's input model.
	ExecutionParameters string `protobuf:"bytes,1,opt,name=executionParameters,proto3" json:"executionParameters,omitempty"`
	// WorkflowRunId is the ID of the workflow run that invoked this data function.
	WorkflowRunId string `protobuf:"bytes,2,opt,name=workflowRunId,proto3" json:"workflowRunId,omitempty"`
	// Uri is the location the data function should stream its output to.
	Uri           string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteDataFunctionRequest) Reset() {
	*x = ExecuteDataFunctionRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDataFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDataFunctionRequest) ProtoMessage() {}

func (x *ExecuteDataFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDataFunctionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteDataFunctionRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteDataFunctionRequest) GetExecutionParameters() string {
	if x != nil {
		return x.ExecutionParameters
	}
	return ""
}

func (x *ExecuteDataFunctionRequest) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *ExecuteDataFunctionRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ExecuteDataFunctionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status indicates whether the data function was successfully started or failed.
	Status ExecutionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ExecutionStatus" json:"status,omitempty"`
	// Message provides detail on why the data function failed to start, if applicable.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteDataFunctionResponse) Reset() {
	*x = ExecuteDataFunctionResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDataFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDataFunctionResponse) ProtoMessage() {}

func (x *ExecuteDataFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDataFunctionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteDataFunctionResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteDataFunctionResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecuteDataFunctionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecuteWorkflowSegmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkflowRunId is the ID generated by the core for this specific workflow run.
	WorkflowRunId string `protobuf:"bytes,1,opt,name=workflowRunId,proto3" json:"workflowRunId,omitempty"`
	// ExecutionParameters is a marshalled JSON struct conforming to the
	// workflow's ExecutionParametersModel schema.
	ExecutionParameters string `protobuf:"bytes,2,opt,name=executionParameters,proto3" json:"executionParameters,omitempty"`
	// DataUri is an optional URI pointing to where the data function's output
	// was stored. Omit if no data function was required.
	DataUri *string `protobuf:"bytes,3,opt,name=dataUri,proto3,oneof" json:"dataUri,omitempty"`
	// Tasks is the ordered set of tasks to execute in this workflow segment.
	Tasks         []*WorkflowTask `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowSegmentRequest) Reset() {
	*x = ExecuteWorkflowSegmentRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowSegmentRequest) ProtoMessage() {}

func (x *ExecuteWorkflowSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowSegmentRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowSegmentRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteWorkflowSegmentRequest) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *ExecuteWorkflowSegmentRequest) GetExecutionParameters() string {
	if x != nil {
		return x.ExecutionParameters
	}
	return ""
}

func (x *ExecuteWorkflowSegmentRequest) GetDataUri() string {
	if x != nil && x.DataUri != nil {
		return *x.DataUri
	}
	return ""
}

func (x *ExecuteWorkflowSegmentRequest) GetTasks() []*WorkflowTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ExecuteWorkflowSegmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status indicates whether the segment executed successfully or failed.
	Status ExecutionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ExecutionStatus" json:"status,omitempty"`
	// Message provides detail on why execution failed, if applicable.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowSegmentResponse) Reset() {
	*x = ExecuteWorkflowSegmentResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowSegmentResponse) ProtoMessage() {}

func (x *ExecuteWorkflowSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowSegmentResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowSegmentResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteWorkflowSegmentResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecuteWorkflowSegmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WorkflowTask describes a single task to execute within a workflow segment.
type WorkflowTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TaskName is the registered name of the task, used to route to the correct handler.
	TaskName string `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	// Parameters is an optional marshalled JSON object of task-specific parameters.
	Parameters    *string `protobuf:"bytes,2,opt,name=parameters,proto3,oneof" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTask) Reset() {
	*x = WorkflowTask{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTask) ProtoMessage() {}

func (x *WorkflowTask) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTask.ProtoReflect.Descriptor instead.
func (*WorkflowTask) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowTask) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *WorkflowTask) GetParameters() string {
	if x != nil && x.Parameters != nil {
		return *x.Parameters
	}
	return ""
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkerId optionally identifies the worker to the core for logging purposes.
	WorkerId      string `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alive confirms the worker is reachable and healthy.
	Alive         bool `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x1a\fshared.proto\"\x86\x01\n" +
	"\x1aExecuteDataFunctionRequest\x120\n" +
	"\x13executionParameters\x18\x01 \x01(\tR\x13executionParameters\x12$\n" +
	"\rworkflowRunId\x18\x02 \x01(\tR\rworkflowRunId\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\"a\n" +
	"\x1bExecuteDataFunctionResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.ExecutionStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc7\x01\n" +
	"\x1dExecuteWorkflowSegmentRequest\x12$\n" +
	"\rworkflowRunId\x18\x01 \x01(\tR\rworkflowRunId\x120\n" +
	"\x13executionParameters\x18\x02 \x01(\tR\x13executionParameters\x12\x1d\n" +
	"\adataUri\x18\x03 \x01(\tH\x00R\adataUri\x88\x01\x01\x12#\n" +
	"\x05tasks\x18\x04 \x03(\v2\r.WorkflowTaskR\x05tasksB\n" +
	"\n" +
	"\b_dataUri\"d\n" +
	"\x1eExecuteWorkflowSegmentResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.ExecutionStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"^\n" +
	"\fWorkflowTask\x12\x1a\n" +
	"\btaskName\x18\x01 \x01(\tR\btaskName\x12#\n" +
	"\n" +
	"parameters\x18\x02 \x01(\tH\x00R\n" +
	"parameters\x88\x01\x01B\r\n" +
	"\v_parameters\".\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\tR\bworkerId\")\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive2\xe9\x01\n" +
	"\x06Worker\x12P\n" +
	"\x13ExecuteDataFunction\x12\x1b.ExecuteDataFunctionRequest\x1a\x1c.ExecuteDataFunctionResponse\x12Y\n" +
	"\x16ExecuteWorkflowSegment\x12\x1e.ExecuteWorkflowSegmentRequest\x1a\x1f.ExecuteWorkflowSegmentResponse\x122\n" +
	"\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponseB'Z%github.com/orca-telemetry/contract/gob\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_worker_proto_goTypes = []any{
	(*ExecuteDataFunctionRequest)(nil),     // 0: ExecuteDataFunctionRequest
	(*ExecuteDataFunctionResponse)(nil),    // 1: ExecuteDataFunctionResponse
	(*ExecuteWorkflowSegmentRequest)(nil),  // 2: ExecuteWorkflowSegmentRequest
	(*ExecuteWorkflowSegmentResponse)(nil), // 3: ExecuteWorkflowSegmentResponse
	(*WorkflowTask)(nil),                   // 4: WorkflowTask
	(*HeartbeatRequest)(nil),               // 5: HeartbeatRequest
	(*HeartbeatResponse)(nil),              // 6: HeartbeatResponse
	(ExecutionStatus)(0),                   // 7: ExecutionStatus
}
var file_worker_proto_depIdxs = []int32{
	7, // 0: ExecuteDataFunctionResponse.status:type_name -> ExecutionStatus
	4, // 1: ExecuteWorkflowSegmentRequest.tasks:type_name -> WorkflowTask
	7, // 2: ExecuteWorkflowSegmentResponse.status:type_name -> ExecutionStatus
	0, // 3: Worker.ExecuteDataFunction:input_type -> ExecuteDataFunctionRequest
	2, // 4: Worker.ExecuteWorkflowSegment:input_type -> ExecuteWorkflowSegmentRequest
	5, // 5: Worker.Heartbeat:input_type -> HeartbeatRequest
	1, // 6: Worker.ExecuteDataFunction:output_type -> ExecuteDataFunctionResponse
	3, // 7: Worker.ExecuteWorkflowSegment:output_type -> ExecuteWorkflowSegmentResponse
	6, // 8: Worker.Heartbeat:output_type -> HeartbeatResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_shared_proto_init()
	file_worker_proto_msgTypes[2].OneofWrappers = []any{}
	file_worker_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
