// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: worker.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker_ExecuteDataFunction_FullMethodName    = "/Worker/ExecuteDataFunction"
	Worker_ExecuteWorkflowSegment_FullMethodName = "/Worker/ExecuteWorkflowSegment"
	Worker_Heartbeat_FullMethodName              = "/Worker/Heartbeat"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker defines the service that a worker must implement to start listening
// for execution requests.
//
// Workers are language-agnostic services that:
// - Execute Data Functions
// - Execute workflow segments, and route them to tasks
//
// Core utilises the workers  to asynchronously schedule task executions (via
// workflow segments) as per the distributed DAG.
type WorkerClient interface {
	// Execute a data function call
	ExecuteDataFunction(ctx context.Context, in *ExecuteDataFunctionRequest, opts ...grpc.CallOption) (*ExecuteDataFunctionResponse, error)
	// Execute a workflow segment (potentially all of it)
	ExecuteWorkflowSegment(ctx context.Context, in *ExecuteWorkflowSegmentRequest, opts ...grpc.CallOption) (*ExecuteWorkflowSegmentResponse, error)
	// Check the liveness of a worker via a simple heartbeat
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) ExecuteDataFunction(ctx context.Context, in *ExecuteDataFunctionRequest, opts ...grpc.CallOption) (*ExecuteDataFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteDataFunctionResponse)
	err := c.cc.Invoke(ctx, Worker_ExecuteDataFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) ExecuteWorkflowSegment(ctx context.Context, in *ExecuteWorkflowSegmentRequest, opts ...grpc.CallOption) (*ExecuteWorkflowSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteWorkflowSegmentResponse)
	err := c.cc.Invoke(ctx, Worker_ExecuteWorkflowSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Worker_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility.
//
// Worker defines the service that a worker must implement to start listening
// for execution requests.
//
// Workers are language-agnostic services that:
// - Execute Data Functions
// - Execute workflow segments, and route them to tasks
//
// Core utilises the workers  to asynchronously schedule task executions (via
// workflow segments) as per the distributed DAG.
type WorkerServer interface {
	// Execute a data function call
	ExecuteDataFunction(context.Context, *ExecuteDataFunctionRequest) (*ExecuteDataFunctionResponse, error)
	// Execute a workflow segment (potentially all of it)
	ExecuteWorkflowSegment(context.Context, *ExecuteWorkflowSegmentRequest) (*ExecuteWorkflowSegmentResponse, error)
	// Check the liveness of a worker via a simple heartbeat
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServer struct{}

func (UnimplementedWorkerServer) ExecuteDataFunction(context.Context, *ExecuteDataFunctionRequest) (*ExecuteDataFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteDataFunction not implemented")
}
func (UnimplementedWorkerServer) ExecuteWorkflowSegment(context.Context, *ExecuteWorkflowSegmentRequest) (*ExecuteWorkflowSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteWorkflowSegment not implemented")
}
func (UnimplementedWorkerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}
func (UnimplementedWorkerServer) testEmbeddedByValue()                {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	// If the following call panics, it indicates UnimplementedWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_ExecuteDataFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDataFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ExecuteDataFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_ExecuteDataFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ExecuteDataFunction(ctx, req.(*ExecuteDataFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_ExecuteWorkflowSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteWorkflowSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ExecuteWorkflowSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_ExecuteWorkflowSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ExecuteWorkflowSegment(ctx, req.(*ExecuteWorkflowSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteDataFunction",
			Handler:    _Worker_ExecuteDataFunction_Handler,
		},
		{
			MethodName: "ExecuteWorkflowSegment",
			Handler:    _Worker_ExecuteWorkflowSegment_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Worker_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
