# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreStub(object):
    """Core is the central orchestration service that:
    - Registers resources such as data functions, tasks and workflows
    - Manages the lifecycle of triggering workflows
    - Coordinates algorithm execution across distributed processors
    - Tracks DAG execution state and handles distributed failure modes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDataFunction = channel.unary_unary(
                '/Core/RegisterDataFunction',
                request_serializer=core__pb2.RegisterDataFunctionRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterDataFunctionResponse.FromString,
                _registered_method=True)
        self.RegisterTask = channel.unary_unary(
                '/Core/RegisterTask',
                request_serializer=core__pb2.RegisterTaskRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterTaskResponse.FromString,
                _registered_method=True)
        self.RegisterWorkflow = channel.unary_unary(
                '/Core/RegisterWorkflow',
                request_serializer=core__pb2.RegisterWorkflowRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterWorkflowResponse.FromString,
                _registered_method=True)
        self.TriggerWorkflow = channel.unary_unary(
                '/Core/TriggerWorkflow',
                request_serializer=core__pb2.TriggerWorkflowRequest.SerializeToString,
                response_deserializer=core__pb2.TriggerWorkflowResponse.FromString,
                _registered_method=True)
        self.RegisterDataFunctionResult = channel.unary_unary(
                '/Core/RegisterDataFunctionResult',
                request_serializer=core__pb2.RegisterDataFunctionCompletionRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterDataFunctionCompletionResponse.FromString,
                _registered_method=True)
        self.RegisterTaskResult = channel.unary_unary(
                '/Core/RegisterTaskResult',
                request_serializer=core__pb2.RegisterTaskResultRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterTaskResultResponse.FromString,
                _registered_method=True)
        self.ExposeState = channel.unary_unary(
                '/Core/ExposeState',
                request_serializer=core__pb2.ExposeStateRequest.SerializeToString,
                response_deserializer=core__pb2.ExposeStateResponse.FromString,
                _registered_method=True)
        self.QueryTaskResult = channel.unary_stream(
                '/Core/QueryTaskResult',
                request_serializer=core__pb2.QueryParams.SerializeToString,
                response_deserializer=core__pb2.PastResults.FromString,
                _registered_method=True)


class CoreServicer(object):
    """Core is the central orchestration service that:
    - Registers resources such as data functions, tasks and workflows
    - Manages the lifecycle of triggering workflows
    - Coordinates algorithm execution across distributed processors
    - Tracks DAG execution state and handles distributed failure modes
    """

    def RegisterDataFunction(self, request, context):
        """Registers a data function available for calling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTask(self, request, context):
        """Registers a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorkflow(self, request, context):
        """Registers a workflow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerWorkflow(self, request, context):
        """Triggers a workflow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDataFunctionResult(self, request, context):
        """Register the completion result of the data function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTaskResult(self, request, context):
        """Registers the result of a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExposeState(self, request, context):
        """Expose the internal state of the orchestration stack
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTaskResult(self, request, context):
        """Query past results of tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDataFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataFunction,
                    request_deserializer=core__pb2.RegisterDataFunctionRequest.FromString,
                    response_serializer=core__pb2.RegisterDataFunctionResponse.SerializeToString,
            ),
            'RegisterTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTask,
                    request_deserializer=core__pb2.RegisterTaskRequest.FromString,
                    response_serializer=core__pb2.RegisterTaskResponse.SerializeToString,
            ),
            'RegisterWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorkflow,
                    request_deserializer=core__pb2.RegisterWorkflowRequest.FromString,
                    response_serializer=core__pb2.RegisterWorkflowResponse.SerializeToString,
            ),
            'TriggerWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerWorkflow,
                    request_deserializer=core__pb2.TriggerWorkflowRequest.FromString,
                    response_serializer=core__pb2.TriggerWorkflowResponse.SerializeToString,
            ),
            'RegisterDataFunctionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataFunctionResult,
                    request_deserializer=core__pb2.RegisterDataFunctionCompletionRequest.FromString,
                    response_serializer=core__pb2.RegisterDataFunctionCompletionResponse.SerializeToString,
            ),
            'RegisterTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTaskResult,
                    request_deserializer=core__pb2.RegisterTaskResultRequest.FromString,
                    response_serializer=core__pb2.RegisterTaskResultResponse.SerializeToString,
            ),
            'ExposeState': grpc.unary_unary_rpc_method_handler(
                    servicer.ExposeState,
                    request_deserializer=core__pb2.ExposeStateRequest.FromString,
                    response_serializer=core__pb2.ExposeStateResponse.SerializeToString,
            ),
            'QueryTaskResult': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryTaskResult,
                    request_deserializer=core__pb2.QueryParams.FromString,
                    response_serializer=core__pb2.PastResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Core', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Core', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Core(object):
    """Core is the central orchestration service that:
    - Registers resources such as data functions, tasks and workflows
    - Manages the lifecycle of triggering workflows
    - Coordinates algorithm execution across distributed processors
    - Tracks DAG execution state and handles distributed failure modes
    """

    @staticmethod
    def RegisterDataFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Core/RegisterDataFunction',
            core__pb2.RegisterDataFunctionRequest.SerializeToString,
            core__pb2.RegisterDataFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Core/RegisterTask',
            core__pb2.RegisterTaskRequest.SerializeToString,
            core__pb2.RegisterTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Core/RegisterWorkflow',
            core__pb2.RegisterWorkflowRequest.SerializeToString,
            core__pb2.RegisterWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Core/TriggerWorkflow',
            core__pb2.TriggerWorkflowRequest.SerializeToString,
            core__pb2.TriggerWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDataFunctionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Core/RegisterDataFunctionResult',
            core__pb2.RegisterDataFunctionCompletionRequest.SerializeToString,
            core__pb2.RegisterDataFunctionCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Core/RegisterTaskResult',
            core__pb2.RegisterTaskResultRequest.SerializeToString,
            core__pb2.RegisterTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExposeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Core/ExposeState',
            core__pb2.ExposeStateRequest.SerializeToString,
            core__pb2.ExposeStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Core/QueryTaskResult',
            core__pb2.QueryParams.SerializeToString,
            core__pb2.PastResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
