# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x1a\x0cshared.proto\"]\n\x1a\x45xecuteDataFunctionRequest\x12\x1b\n\x13\x65xecutionParameters\x18\x01 \x01(\t\x12\x15\n\rworkflowRunId\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x03 \x01(\t\"P\n\x1b\x45xecuteDataFunctionResponse\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.ExecutionStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x93\x01\n\x1d\x45xecuteWorkflowSegmentRequest\x12\x15\n\rworkflowRunId\x18\x01 \x01(\t\x12\x1b\n\x13\x65xecutionParameters\x18\x02 \x01(\t\x12\x14\n\x07\x64\x61taUri\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x05tasks\x18\x04 \x03(\x0b\x32\r.WorkflowTaskB\n\n\x08_dataUri\"S\n\x1e\x45xecuteWorkflowSegmentResponse\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.ExecutionStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\"H\n\x0cWorkflowTask\x12\x10\n\x08taskName\x18\x01 \x01(\t\x12\x17\n\nparameters\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_parameters\"$\n\x10HeartbeatRequest\x12\x10\n\x08workerId\x18\x01 \x01(\t\"\"\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\xe9\x01\n\x06Worker\x12P\n\x13\x45xecuteDataFunction\x12\x1b.ExecuteDataFunctionRequest\x1a\x1c.ExecuteDataFunctionResponse\x12Y\n\x16\x45xecuteWorkflowSegment\x12\x1e.ExecuteWorkflowSegmentRequest\x1a\x1f.ExecuteWorkflowSegmentResponse\x12\x32\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponseB\'Z%github.com/orca-telemetry/contract/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/orca-telemetry/contract/go'
  _globals['_EXECUTEDATAFUNCTIONREQUEST']._serialized_start=30
  _globals['_EXECUTEDATAFUNCTIONREQUEST']._serialized_end=123
  _globals['_EXECUTEDATAFUNCTIONRESPONSE']._serialized_start=125
  _globals['_EXECUTEDATAFUNCTIONRESPONSE']._serialized_end=205
  _globals['_EXECUTEWORKFLOWSEGMENTREQUEST']._serialized_start=208
  _globals['_EXECUTEWORKFLOWSEGMENTREQUEST']._serialized_end=355
  _globals['_EXECUTEWORKFLOWSEGMENTRESPONSE']._serialized_start=357
  _globals['_EXECUTEWORKFLOWSEGMENTRESPONSE']._serialized_end=440
  _globals['_WORKFLOWTASK']._serialized_start=442
  _globals['_WORKFLOWTASK']._serialized_end=514
  _globals['_HEARTBEATREQUEST']._serialized_start=516
  _globals['_HEARTBEATREQUEST']._serialized_end=552
  _globals['_HEARTBEATRESPONSE']._serialized_start=554
  _globals['_HEARTBEATRESPONSE']._serialized_end=588
  _globals['_WORKER']._serialized_start=591
  _globals['_WORKER']._serialized_end=824
# @@protoc_insertion_point(module_scope)
