# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerStub(object):
    """Worker defines the service that a worker must implement to start listening
    for execution requests.

    Workers are language-agnostic services that:
    - Execute Data Functions
    - Execute workflow segments, and route them to tasks

    Core utilises the workers  to asynchronously schedule task executions (via
    workflow segments) as per the distributed DAG.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteDataFunction = channel.unary_unary(
                '/Worker/ExecuteDataFunction',
                request_serializer=worker__pb2.ExecuteDataFunctionRequest.SerializeToString,
                response_deserializer=worker__pb2.ExecuteDataFunctionResponse.FromString,
                _registered_method=True)
        self.ExecuteWorkflowSegment = channel.unary_unary(
                '/Worker/ExecuteWorkflowSegment',
                request_serializer=worker__pb2.ExecuteWorkflowSegmentRequest.SerializeToString,
                response_deserializer=worker__pb2.ExecuteWorkflowSegmentResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/Worker/Heartbeat',
                request_serializer=worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class WorkerServicer(object):
    """Worker defines the service that a worker must implement to start listening
    for execution requests.

    Workers are language-agnostic services that:
    - Execute Data Functions
    - Execute workflow segments, and route them to tasks

    Core utilises the workers  to asynchronously schedule task executions (via
    workflow segments) as per the distributed DAG.
    """

    def ExecuteDataFunction(self, request, context):
        """Execute a data function call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWorkflowSegment(self, request, context):
        """Execute a workflow segment (potentially all of it)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Check the liveness of a worker via a simple heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteDataFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteDataFunction,
                    request_deserializer=worker__pb2.ExecuteDataFunctionRequest.FromString,
                    response_serializer=worker__pb2.ExecuteDataFunctionResponse.SerializeToString,
            ),
            'ExecuteWorkflowSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorkflowSegment,
                    request_deserializer=worker__pb2.ExecuteWorkflowSegmentRequest.FromString,
                    response_serializer=worker__pb2.ExecuteWorkflowSegmentResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=worker__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """Worker defines the service that a worker must implement to start listening
    for execution requests.

    Workers are language-agnostic services that:
    - Execute Data Functions
    - Execute workflow segments, and route them to tasks

    Core utilises the workers  to asynchronously schedule task executions (via
    workflow segments) as per the distributed DAG.
    """

    @staticmethod
    def ExecuteDataFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Worker/ExecuteDataFunction',
            worker__pb2.ExecuteDataFunctionRequest.SerializeToString,
            worker__pb2.ExecuteDataFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteWorkflowSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Worker/ExecuteWorkflowSegment',
            worker__pb2.ExecuteWorkflowSegmentRequest.SerializeToString,
            worker__pb2.ExecuteWorkflowSegmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Worker/Heartbeat',
            worker__pb2.HeartbeatRequest.SerializeToString,
            worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
