// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: shared.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

/** TriggerSource denotes the origin of a workflow trigger event. */
export enum TriggerSource {
  TRIGGER_SOURCE_UNSPECIFIED = 0,
  TRIGGER_SOURCE_CRON = 1,
  TRIGGER_SOURCE_WEBHOOK = 2,
  TRIGGER_SOURCE_UI = 3,
  TRIGGER_SOURCE_CLI = 4,
  UNRECOGNIZED = -1,
}

export function triggerSourceFromJSON(object: any): TriggerSource {
  switch (object) {
    case 0:
    case "TRIGGER_SOURCE_UNSPECIFIED":
      return TriggerSource.TRIGGER_SOURCE_UNSPECIFIED;
    case 1:
    case "TRIGGER_SOURCE_CRON":
      return TriggerSource.TRIGGER_SOURCE_CRON;
    case 2:
    case "TRIGGER_SOURCE_WEBHOOK":
      return TriggerSource.TRIGGER_SOURCE_WEBHOOK;
    case 3:
    case "TRIGGER_SOURCE_UI":
      return TriggerSource.TRIGGER_SOURCE_UI;
    case 4:
    case "TRIGGER_SOURCE_CLI":
      return TriggerSource.TRIGGER_SOURCE_CLI;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TriggerSource.UNRECOGNIZED;
  }
}

export function triggerSourceToJSON(object: TriggerSource): string {
  switch (object) {
    case TriggerSource.TRIGGER_SOURCE_UNSPECIFIED:
      return "TRIGGER_SOURCE_UNSPECIFIED";
    case TriggerSource.TRIGGER_SOURCE_CRON:
      return "TRIGGER_SOURCE_CRON";
    case TriggerSource.TRIGGER_SOURCE_WEBHOOK:
      return "TRIGGER_SOURCE_WEBHOOK";
    case TriggerSource.TRIGGER_SOURCE_UI:
      return "TRIGGER_SOURCE_UI";
    case TriggerSource.TRIGGER_SOURCE_CLI:
      return "TRIGGER_SOURCE_CLI";
    case TriggerSource.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** TriggerStatus is the result of a workflow trigger RPC. */
export enum TriggerStatus {
  TRIGGER_STATUS_UNSPECIFIED = 0,
  TRIGGER_STATUS_ACCEPTED = 1,
  TRIGGER_STATUS_REJECTED = 2,
  UNRECOGNIZED = -1,
}

export function triggerStatusFromJSON(object: any): TriggerStatus {
  switch (object) {
    case 0:
    case "TRIGGER_STATUS_UNSPECIFIED":
      return TriggerStatus.TRIGGER_STATUS_UNSPECIFIED;
    case 1:
    case "TRIGGER_STATUS_ACCEPTED":
      return TriggerStatus.TRIGGER_STATUS_ACCEPTED;
    case 2:
    case "TRIGGER_STATUS_REJECTED":
      return TriggerStatus.TRIGGER_STATUS_REJECTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TriggerStatus.UNRECOGNIZED;
  }
}

export function triggerStatusToJSON(object: TriggerStatus): string {
  switch (object) {
    case TriggerStatus.TRIGGER_STATUS_UNSPECIFIED:
      return "TRIGGER_STATUS_UNSPECIFIED";
    case TriggerStatus.TRIGGER_STATUS_ACCEPTED:
      return "TRIGGER_STATUS_ACCEPTED";
    case TriggerStatus.TRIGGER_STATUS_REJECTED:
      return "TRIGGER_STATUS_REJECTED";
    case TriggerStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ExecutionStatus is the result of a task or data function execution. */
export enum ExecutionStatus {
  EXECUTION_STATUS_UNSPECIFIED = 0,
  EXECUTION_STATUS_SUCCESSFUL = 1,
  EXECUTION_STATUS_FAILED = 2,
  UNRECOGNIZED = -1,
}

export function executionStatusFromJSON(object: any): ExecutionStatus {
  switch (object) {
    case 0:
    case "EXECUTION_STATUS_UNSPECIFIED":
      return ExecutionStatus.EXECUTION_STATUS_UNSPECIFIED;
    case 1:
    case "EXECUTION_STATUS_SUCCESSFUL":
      return ExecutionStatus.EXECUTION_STATUS_SUCCESSFUL;
    case 2:
    case "EXECUTION_STATUS_FAILED":
      return ExecutionStatus.EXECUTION_STATUS_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExecutionStatus.UNRECOGNIZED;
  }
}

export function executionStatusToJSON(object: ExecutionStatus): string {
  switch (object) {
    case ExecutionStatus.EXECUTION_STATUS_UNSPECIFIED:
      return "EXECUTION_STATUS_UNSPECIFIED";
    case ExecutionStatus.EXECUTION_STATUS_SUCCESSFUL:
      return "EXECUTION_STATUS_SUCCESSFUL";
    case ExecutionStatus.EXECUTION_STATUS_FAILED:
      return "EXECUTION_STATUS_FAILED";
    case ExecutionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** BackoffStrategy defines the retry backoff behaviour for a task. */
export enum BackoffStrategy {
  BACKOFF_STRATEGY_UNSPECIFIED = 0,
  BACKOFF_STRATEGY_LINEAR = 1,
  BACKOFF_STRATEGY_EXPONENTIAL = 2,
  UNRECOGNIZED = -1,
}

export function backoffStrategyFromJSON(object: any): BackoffStrategy {
  switch (object) {
    case 0:
    case "BACKOFF_STRATEGY_UNSPECIFIED":
      return BackoffStrategy.BACKOFF_STRATEGY_UNSPECIFIED;
    case 1:
    case "BACKOFF_STRATEGY_LINEAR":
      return BackoffStrategy.BACKOFF_STRATEGY_LINEAR;
    case 2:
    case "BACKOFF_STRATEGY_EXPONENTIAL":
      return BackoffStrategy.BACKOFF_STRATEGY_EXPONENTIAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BackoffStrategy.UNRECOGNIZED;
  }
}

export function backoffStrategyToJSON(object: BackoffStrategy): string {
  switch (object) {
    case BackoffStrategy.BACKOFF_STRATEGY_UNSPECIFIED:
      return "BACKOFF_STRATEGY_UNSPECIFIED";
    case BackoffStrategy.BACKOFF_STRATEGY_LINEAR:
      return "BACKOFF_STRATEGY_LINEAR";
    case BackoffStrategy.BACKOFF_STRATEGY_EXPONENTIAL:
      return "BACKOFF_STRATEGY_EXPONENTIAL";
    case BackoffStrategy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * DataFunctionSettings holds configuration that governs the lifecycle of
 * data produced by a data function.
 */
export interface DataFunctionSettings {
  /**
   * TTL controls how long produced data is retained.
   * 0 = clean up immediately after DAG execution of all dependent tasks completes.
   * >0 = retention duration in seconds.
   */
  ttl?:
    | number
    | undefined;
  /**
   * Timeout is the maximum duration (in seconds) allowed for the data
   * function's full lifecycle.
   */
  timeout?: number | undefined;
}

/** TaskExecutionSettings governs how a task is executed and retried. */
export interface TaskExecutionSettings {
  /**
   * ExecutionTimeout is the maximum duration (in seconds) allowed for a
   * single task execution attempt.
   */
  executionTimeout?:
    | number
    | undefined;
  /** RetryCount is the number of times the task should be retried on failure. */
  retryCount?:
    | number
    | undefined;
  /** BackoffStrategy defines whether retries use linear or exponential backoff. */
  backoffStrategy?:
    | BackoffStrategy
    | undefined;
  /**
   * Deadline is an SLA value in seconds. If execution exceeds this deadline,
   * an alert is raised against this task's execution status.
   */
  deadline?: number | undefined;
}

/**
 * RequiredPastResult describes a prior task result that must be available
 * before the owning task can execute.
 */
export interface RequiredPastResult {
  /** TaskName is the name of the task whose prior result is required. */
  taskName?:
    | string
    | undefined;
  /**
   * ExecutionParams is the marshalled JSON of the execution parameters
   * used when the referenced workflow was triggered.
   */
  executionParams?:
    | string
    | undefined;
  /** TaskResult is the expected result value of the referenced task execution. */
  taskResult?: string | undefined;
}

/**
 * WorkflowExecutionSettings defines pipeline-level concurrency and
 * prioritisation configuration.
 */
export interface WorkflowExecutionSettings {
  /**
   * PriorityQueue lists tasks that should be prioritised over others
   * during parallel execution.
   */
  priorityQueue?:
    | string[]
    | undefined;
  /**
   * ConcurrencyLimit caps the number of tasks that may execute in
   * parallel at any point in time.
   */
  concurrencyLimit?: number | undefined;
}

/** ComputeMetrics captures resource consumption for a single task execution. */
export interface ComputeMetrics {
  /** CpuSeconds is the total CPU time consumed, measured in CPU-seconds. */
  cpuSeconds?:
    | number
    | undefined;
  /** MemoryGiBSeconds is the total memory consumed, measured in GiB-seconds. */
  memoryGiBSeconds?: number | undefined;
}

function createBaseDataFunctionSettings(): DataFunctionSettings {
  return { ttl: 0, timeout: 0 };
}

export const DataFunctionSettings: MessageFns<DataFunctionSettings> = {
  encode(message: DataFunctionSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ttl !== undefined && message.ttl !== 0) {
      writer.uint32(8).int32(message.ttl);
    }
    if (message.timeout !== undefined && message.timeout !== 0) {
      writer.uint32(16).int32(message.timeout);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataFunctionSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataFunctionSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ttl = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timeout = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataFunctionSettings {
    return {
      ttl: isSet(object.ttl) ? globalThis.Number(object.ttl) : 0,
      timeout: isSet(object.timeout) ? globalThis.Number(object.timeout) : 0,
    };
  },

  toJSON(message: DataFunctionSettings): unknown {
    const obj: any = {};
    if (message.ttl !== undefined && message.ttl !== 0) {
      obj.ttl = Math.round(message.ttl);
    }
    if (message.timeout !== undefined && message.timeout !== 0) {
      obj.timeout = Math.round(message.timeout);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataFunctionSettings>, I>>(base?: I): DataFunctionSettings {
    return DataFunctionSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataFunctionSettings>, I>>(object: I): DataFunctionSettings {
    const message = createBaseDataFunctionSettings();
    message.ttl = object.ttl ?? 0;
    message.timeout = object.timeout ?? 0;
    return message;
  },
};

function createBaseTaskExecutionSettings(): TaskExecutionSettings {
  return { executionTimeout: 0, retryCount: 0, backoffStrategy: 0, deadline: 0 };
}

export const TaskExecutionSettings: MessageFns<TaskExecutionSettings> = {
  encode(message: TaskExecutionSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.executionTimeout !== undefined && message.executionTimeout !== 0) {
      writer.uint32(8).int32(message.executionTimeout);
    }
    if (message.retryCount !== undefined && message.retryCount !== 0) {
      writer.uint32(16).int32(message.retryCount);
    }
    if (message.backoffStrategy !== undefined && message.backoffStrategy !== 0) {
      writer.uint32(24).int32(message.backoffStrategy);
    }
    if (message.deadline !== undefined && message.deadline !== 0) {
      writer.uint32(32).int32(message.deadline);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskExecutionSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskExecutionSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.executionTimeout = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.retryCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.backoffStrategy = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.deadline = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskExecutionSettings {
    return {
      executionTimeout: isSet(object.executionTimeout) ? globalThis.Number(object.executionTimeout) : 0,
      retryCount: isSet(object.retryCount) ? globalThis.Number(object.retryCount) : 0,
      backoffStrategy: isSet(object.backoffStrategy) ? backoffStrategyFromJSON(object.backoffStrategy) : 0,
      deadline: isSet(object.deadline) ? globalThis.Number(object.deadline) : 0,
    };
  },

  toJSON(message: TaskExecutionSettings): unknown {
    const obj: any = {};
    if (message.executionTimeout !== undefined && message.executionTimeout !== 0) {
      obj.executionTimeout = Math.round(message.executionTimeout);
    }
    if (message.retryCount !== undefined && message.retryCount !== 0) {
      obj.retryCount = Math.round(message.retryCount);
    }
    if (message.backoffStrategy !== undefined && message.backoffStrategy !== 0) {
      obj.backoffStrategy = backoffStrategyToJSON(message.backoffStrategy);
    }
    if (message.deadline !== undefined && message.deadline !== 0) {
      obj.deadline = Math.round(message.deadline);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskExecutionSettings>, I>>(base?: I): TaskExecutionSettings {
    return TaskExecutionSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskExecutionSettings>, I>>(object: I): TaskExecutionSettings {
    const message = createBaseTaskExecutionSettings();
    message.executionTimeout = object.executionTimeout ?? 0;
    message.retryCount = object.retryCount ?? 0;
    message.backoffStrategy = object.backoffStrategy ?? 0;
    message.deadline = object.deadline ?? 0;
    return message;
  },
};

function createBaseRequiredPastResult(): RequiredPastResult {
  return { taskName: "", executionParams: "", taskResult: "" };
}

export const RequiredPastResult: MessageFns<RequiredPastResult> = {
  encode(message: RequiredPastResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskName !== undefined && message.taskName !== "") {
      writer.uint32(10).string(message.taskName);
    }
    if (message.executionParams !== undefined && message.executionParams !== "") {
      writer.uint32(18).string(message.executionParams);
    }
    if (message.taskResult !== undefined && message.taskResult !== "") {
      writer.uint32(26).string(message.taskResult);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequiredPastResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequiredPastResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.executionParams = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.taskResult = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequiredPastResult {
    return {
      taskName: isSet(object.taskName) ? globalThis.String(object.taskName) : "",
      executionParams: isSet(object.executionParams) ? globalThis.String(object.executionParams) : "",
      taskResult: isSet(object.taskResult) ? globalThis.String(object.taskResult) : "",
    };
  },

  toJSON(message: RequiredPastResult): unknown {
    const obj: any = {};
    if (message.taskName !== undefined && message.taskName !== "") {
      obj.taskName = message.taskName;
    }
    if (message.executionParams !== undefined && message.executionParams !== "") {
      obj.executionParams = message.executionParams;
    }
    if (message.taskResult !== undefined && message.taskResult !== "") {
      obj.taskResult = message.taskResult;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequiredPastResult>, I>>(base?: I): RequiredPastResult {
    return RequiredPastResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequiredPastResult>, I>>(object: I): RequiredPastResult {
    const message = createBaseRequiredPastResult();
    message.taskName = object.taskName ?? "";
    message.executionParams = object.executionParams ?? "";
    message.taskResult = object.taskResult ?? "";
    return message;
  },
};

function createBaseWorkflowExecutionSettings(): WorkflowExecutionSettings {
  return { priorityQueue: [], concurrencyLimit: 0 };
}

export const WorkflowExecutionSettings: MessageFns<WorkflowExecutionSettings> = {
  encode(message: WorkflowExecutionSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.priorityQueue !== undefined && message.priorityQueue.length !== 0) {
      for (const v of message.priorityQueue) {
        writer.uint32(10).string(v!);
      }
    }
    if (message.concurrencyLimit !== undefined && message.concurrencyLimit !== 0) {
      writer.uint32(16).int32(message.concurrencyLimit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkflowExecutionSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkflowExecutionSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const el = reader.string();
          if (el !== undefined) {
            message.priorityQueue!.push(el);
          }
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.concurrencyLimit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkflowExecutionSettings {
    return {
      priorityQueue: globalThis.Array.isArray(object?.priorityQueue)
        ? object.priorityQueue.map((e: any) => globalThis.String(e))
        : [],
      concurrencyLimit: isSet(object.concurrencyLimit) ? globalThis.Number(object.concurrencyLimit) : 0,
    };
  },

  toJSON(message: WorkflowExecutionSettings): unknown {
    const obj: any = {};
    if (message.priorityQueue?.length) {
      obj.priorityQueue = message.priorityQueue;
    }
    if (message.concurrencyLimit !== undefined && message.concurrencyLimit !== 0) {
      obj.concurrencyLimit = Math.round(message.concurrencyLimit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkflowExecutionSettings>, I>>(base?: I): WorkflowExecutionSettings {
    return WorkflowExecutionSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkflowExecutionSettings>, I>>(object: I): WorkflowExecutionSettings {
    const message = createBaseWorkflowExecutionSettings();
    message.priorityQueue = object.priorityQueue?.map((e) => e) || [];
    message.concurrencyLimit = object.concurrencyLimit ?? 0;
    return message;
  },
};

function createBaseComputeMetrics(): ComputeMetrics {
  return { cpuSeconds: 0, memoryGiBSeconds: 0 };
}

export const ComputeMetrics: MessageFns<ComputeMetrics> = {
  encode(message: ComputeMetrics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cpuSeconds !== undefined && message.cpuSeconds !== 0) {
      writer.uint32(9).double(message.cpuSeconds);
    }
    if (message.memoryGiBSeconds !== undefined && message.memoryGiBSeconds !== 0) {
      writer.uint32(17).double(message.memoryGiBSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ComputeMetrics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComputeMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.cpuSeconds = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.memoryGiBSeconds = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ComputeMetrics {
    return {
      cpuSeconds: isSet(object.cpuSeconds) ? globalThis.Number(object.cpuSeconds) : 0,
      memoryGiBSeconds: isSet(object.memoryGiBSeconds) ? globalThis.Number(object.memoryGiBSeconds) : 0,
    };
  },

  toJSON(message: ComputeMetrics): unknown {
    const obj: any = {};
    if (message.cpuSeconds !== undefined && message.cpuSeconds !== 0) {
      obj.cpuSeconds = message.cpuSeconds;
    }
    if (message.memoryGiBSeconds !== undefined && message.memoryGiBSeconds !== 0) {
      obj.memoryGiBSeconds = message.memoryGiBSeconds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ComputeMetrics>, I>>(base?: I): ComputeMetrics {
    return ComputeMetrics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ComputeMetrics>, I>>(object: I): ComputeMetrics {
    const message = createBaseComputeMetrics();
    message.cpuSeconds = object.cpuSeconds ?? 0;
    message.memoryGiBSeconds = object.memoryGiBSeconds ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
