// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.9
// source: worker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { ExecutionStatus, executionStatusFromJSON, executionStatusToJSON } from "./shared";

export const protobufPackage = "";

export interface ExecuteDataFunctionRequest {
  /**
   * ExecutionParameters is a marshalled JSON struct conforming to the data
   * function's input model.
   */
  executionParameters?:
    | string
    | undefined;
  /** WorkflowRunId is the ID of the workflow run that invoked this data function. */
  workflowRunId?:
    | string
    | undefined;
  /** Uri is the location the data function should stream its output to. */
  uri?: string | undefined;
}

export interface ExecuteDataFunctionResponse {
  /** Status indicates whether the data function was successfully started or failed. */
  status?:
    | ExecutionStatus
    | undefined;
  /** Message provides detail on why the data function failed to start, if applicable. */
  message?: string | undefined;
}

export interface ExecuteWorkflowSegmentRequest {
  /** WorkflowRunId is the ID generated by the core for this specific workflow run. */
  workflowRunId?:
    | string
    | undefined;
  /**
   * ExecutionParameters is a marshalled JSON struct conforming to the
   * workflow's ExecutionParametersModel schema.
   */
  executionParameters?:
    | string
    | undefined;
  /**
   * DataUri is an optional URI pointing to where the data function's output
   * was stored. Omit if no data function was required.
   */
  dataUri?:
    | string
    | undefined;
  /** Tasks is the ordered set of tasks to execute in this workflow segment. */
  tasks?: WorkflowTask[] | undefined;
}

export interface ExecuteWorkflowSegmentResponse {
  /** Status indicates whether the segment executed successfully or failed. */
  status?:
    | ExecutionStatus
    | undefined;
  /** Message provides detail on why execution failed, if applicable. */
  message?: string | undefined;
}

/** WorkflowTask describes a single task to execute within a workflow segment. */
export interface WorkflowTask {
  /** TaskName is the registered name of the task, used to route to the correct handler. */
  taskName?:
    | string
    | undefined;
  /** Parameters is an optional marshalled JSON object of task-specific parameters. */
  parameters?: string | undefined;
}

export interface HeartbeatRequest {
  /** WorkerId optionally identifies the worker to the core for logging purposes. */
  workerId?: string | undefined;
}

export interface HeartbeatResponse {
  /** Alive confirms the worker is reachable and healthy. */
  alive?: boolean | undefined;
}

function createBaseExecuteDataFunctionRequest(): ExecuteDataFunctionRequest {
  return { executionParameters: "", workflowRunId: "", uri: "" };
}

export const ExecuteDataFunctionRequest: MessageFns<ExecuteDataFunctionRequest> = {
  encode(message: ExecuteDataFunctionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.executionParameters !== undefined && message.executionParameters !== "") {
      writer.uint32(10).string(message.executionParameters);
    }
    if (message.workflowRunId !== undefined && message.workflowRunId !== "") {
      writer.uint32(18).string(message.workflowRunId);
    }
    if (message.uri !== undefined && message.uri !== "") {
      writer.uint32(26).string(message.uri);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteDataFunctionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteDataFunctionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.executionParameters = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workflowRunId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.uri = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteDataFunctionRequest {
    return {
      executionParameters: isSet(object.executionParameters) ? globalThis.String(object.executionParameters) : "",
      workflowRunId: isSet(object.workflowRunId) ? globalThis.String(object.workflowRunId) : "",
      uri: isSet(object.uri) ? globalThis.String(object.uri) : "",
    };
  },

  toJSON(message: ExecuteDataFunctionRequest): unknown {
    const obj: any = {};
    if (message.executionParameters !== undefined && message.executionParameters !== "") {
      obj.executionParameters = message.executionParameters;
    }
    if (message.workflowRunId !== undefined && message.workflowRunId !== "") {
      obj.workflowRunId = message.workflowRunId;
    }
    if (message.uri !== undefined && message.uri !== "") {
      obj.uri = message.uri;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteDataFunctionRequest>, I>>(base?: I): ExecuteDataFunctionRequest {
    return ExecuteDataFunctionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteDataFunctionRequest>, I>>(object: I): ExecuteDataFunctionRequest {
    const message = createBaseExecuteDataFunctionRequest();
    message.executionParameters = object.executionParameters ?? "";
    message.workflowRunId = object.workflowRunId ?? "";
    message.uri = object.uri ?? "";
    return message;
  },
};

function createBaseExecuteDataFunctionResponse(): ExecuteDataFunctionResponse {
  return { status: 0, message: "" };
}

export const ExecuteDataFunctionResponse: MessageFns<ExecuteDataFunctionResponse> = {
  encode(message: ExecuteDataFunctionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined && message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.message !== undefined && message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteDataFunctionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteDataFunctionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteDataFunctionResponse {
    return {
      status: isSet(object.status) ? executionStatusFromJSON(object.status) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: ExecuteDataFunctionResponse): unknown {
    const obj: any = {};
    if (message.status !== undefined && message.status !== 0) {
      obj.status = executionStatusToJSON(message.status);
    }
    if (message.message !== undefined && message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteDataFunctionResponse>, I>>(base?: I): ExecuteDataFunctionResponse {
    return ExecuteDataFunctionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteDataFunctionResponse>, I>>(object: I): ExecuteDataFunctionResponse {
    const message = createBaseExecuteDataFunctionResponse();
    message.status = object.status ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseExecuteWorkflowSegmentRequest(): ExecuteWorkflowSegmentRequest {
  return { workflowRunId: "", executionParameters: "", dataUri: undefined, tasks: [] };
}

export const ExecuteWorkflowSegmentRequest: MessageFns<ExecuteWorkflowSegmentRequest> = {
  encode(message: ExecuteWorkflowSegmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workflowRunId !== undefined && message.workflowRunId !== "") {
      writer.uint32(10).string(message.workflowRunId);
    }
    if (message.executionParameters !== undefined && message.executionParameters !== "") {
      writer.uint32(18).string(message.executionParameters);
    }
    if (message.dataUri !== undefined) {
      writer.uint32(26).string(message.dataUri);
    }
    if (message.tasks !== undefined && message.tasks.length !== 0) {
      for (const v of message.tasks) {
        WorkflowTask.encode(v!, writer.uint32(34).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteWorkflowSegmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteWorkflowSegmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workflowRunId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.executionParameters = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dataUri = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const el = WorkflowTask.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.tasks!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteWorkflowSegmentRequest {
    return {
      workflowRunId: isSet(object.workflowRunId) ? globalThis.String(object.workflowRunId) : "",
      executionParameters: isSet(object.executionParameters) ? globalThis.String(object.executionParameters) : "",
      dataUri: isSet(object.dataUri) ? globalThis.String(object.dataUri) : undefined,
      tasks: globalThis.Array.isArray(object?.tasks) ? object.tasks.map((e: any) => WorkflowTask.fromJSON(e)) : [],
    };
  },

  toJSON(message: ExecuteWorkflowSegmentRequest): unknown {
    const obj: any = {};
    if (message.workflowRunId !== undefined && message.workflowRunId !== "") {
      obj.workflowRunId = message.workflowRunId;
    }
    if (message.executionParameters !== undefined && message.executionParameters !== "") {
      obj.executionParameters = message.executionParameters;
    }
    if (message.dataUri !== undefined) {
      obj.dataUri = message.dataUri;
    }
    if (message.tasks?.length) {
      obj.tasks = message.tasks.map((e) => WorkflowTask.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteWorkflowSegmentRequest>, I>>(base?: I): ExecuteWorkflowSegmentRequest {
    return ExecuteWorkflowSegmentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteWorkflowSegmentRequest>, I>>(
    object: I,
  ): ExecuteWorkflowSegmentRequest {
    const message = createBaseExecuteWorkflowSegmentRequest();
    message.workflowRunId = object.workflowRunId ?? "";
    message.executionParameters = object.executionParameters ?? "";
    message.dataUri = object.dataUri ?? undefined;
    message.tasks = object.tasks?.map((e) => WorkflowTask.fromPartial(e)) || [];
    return message;
  },
};

function createBaseExecuteWorkflowSegmentResponse(): ExecuteWorkflowSegmentResponse {
  return { status: 0, message: "" };
}

export const ExecuteWorkflowSegmentResponse: MessageFns<ExecuteWorkflowSegmentResponse> = {
  encode(message: ExecuteWorkflowSegmentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined && message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.message !== undefined && message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteWorkflowSegmentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteWorkflowSegmentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteWorkflowSegmentResponse {
    return {
      status: isSet(object.status) ? executionStatusFromJSON(object.status) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: ExecuteWorkflowSegmentResponse): unknown {
    const obj: any = {};
    if (message.status !== undefined && message.status !== 0) {
      obj.status = executionStatusToJSON(message.status);
    }
    if (message.message !== undefined && message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteWorkflowSegmentResponse>, I>>(base?: I): ExecuteWorkflowSegmentResponse {
    return ExecuteWorkflowSegmentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteWorkflowSegmentResponse>, I>>(
    object: I,
  ): ExecuteWorkflowSegmentResponse {
    const message = createBaseExecuteWorkflowSegmentResponse();
    message.status = object.status ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseWorkflowTask(): WorkflowTask {
  return { taskName: "", parameters: undefined };
}

export const WorkflowTask: MessageFns<WorkflowTask> = {
  encode(message: WorkflowTask, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskName !== undefined && message.taskName !== "") {
      writer.uint32(10).string(message.taskName);
    }
    if (message.parameters !== undefined) {
      writer.uint32(18).string(message.parameters);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkflowTask {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkflowTask();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parameters = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkflowTask {
    return {
      taskName: isSet(object.taskName) ? globalThis.String(object.taskName) : "",
      parameters: isSet(object.parameters) ? globalThis.String(object.parameters) : undefined,
    };
  },

  toJSON(message: WorkflowTask): unknown {
    const obj: any = {};
    if (message.taskName !== undefined && message.taskName !== "") {
      obj.taskName = message.taskName;
    }
    if (message.parameters !== undefined) {
      obj.parameters = message.parameters;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkflowTask>, I>>(base?: I): WorkflowTask {
    return WorkflowTask.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkflowTask>, I>>(object: I): WorkflowTask {
    const message = createBaseWorkflowTask();
    message.taskName = object.taskName ?? "";
    message.parameters = object.parameters ?? undefined;
    return message;
  },
};

function createBaseHeartbeatRequest(): HeartbeatRequest {
  return { workerId: "" };
}

export const HeartbeatRequest: MessageFns<HeartbeatRequest> = {
  encode(message: HeartbeatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workerId !== undefined && message.workerId !== "") {
      writer.uint32(10).string(message.workerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartbeatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeartbeatRequest {
    return { workerId: isSet(object.workerId) ? globalThis.String(object.workerId) : "" };
  },

  toJSON(message: HeartbeatRequest): unknown {
    const obj: any = {};
    if (message.workerId !== undefined && message.workerId !== "") {
      obj.workerId = message.workerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeartbeatRequest>, I>>(base?: I): HeartbeatRequest {
    return HeartbeatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeartbeatRequest>, I>>(object: I): HeartbeatRequest {
    const message = createBaseHeartbeatRequest();
    message.workerId = object.workerId ?? "";
    return message;
  },
};

function createBaseHeartbeatResponse(): HeartbeatResponse {
  return { alive: false };
}

export const HeartbeatResponse: MessageFns<HeartbeatResponse> = {
  encode(message: HeartbeatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.alive !== undefined && message.alive !== false) {
      writer.uint32(8).bool(message.alive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartbeatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.alive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeartbeatResponse {
    return { alive: isSet(object.alive) ? globalThis.Boolean(object.alive) : false };
  },

  toJSON(message: HeartbeatResponse): unknown {
    const obj: any = {};
    if (message.alive !== undefined && message.alive !== false) {
      obj.alive = message.alive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeartbeatResponse>, I>>(base?: I): HeartbeatResponse {
    return HeartbeatResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeartbeatResponse>, I>>(object: I): HeartbeatResponse {
    const message = createBaseHeartbeatResponse();
    message.alive = object.alive ?? false;
    return message;
  },
};

/**
 * Worker defines the service that a worker must implement to start listening
 * for execution requests.
 *
 * Workers are language-agnostic services that:
 * - Execute Data Functions
 * - Execute workflow segments, and route them to tasks
 *
 * Core utilises the workers  to asynchronously schedule task executions (via
 * workflow segments) as per the distributed DAG.
 */
export type WorkerService = typeof WorkerService;
export const WorkerService = {
  /** Execute a data function call */
  executeDataFunction: {
    path: "/Worker/ExecuteDataFunction" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ExecuteDataFunctionRequest): Buffer =>
      Buffer.from(ExecuteDataFunctionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ExecuteDataFunctionRequest => ExecuteDataFunctionRequest.decode(value),
    responseSerialize: (value: ExecuteDataFunctionResponse): Buffer =>
      Buffer.from(ExecuteDataFunctionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ExecuteDataFunctionResponse => ExecuteDataFunctionResponse.decode(value),
  },
  /** Execute a workflow segment (potentially all of it) */
  executeWorkflowSegment: {
    path: "/Worker/ExecuteWorkflowSegment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ExecuteWorkflowSegmentRequest): Buffer =>
      Buffer.from(ExecuteWorkflowSegmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ExecuteWorkflowSegmentRequest => ExecuteWorkflowSegmentRequest.decode(value),
    responseSerialize: (value: ExecuteWorkflowSegmentResponse): Buffer =>
      Buffer.from(ExecuteWorkflowSegmentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ExecuteWorkflowSegmentResponse =>
      ExecuteWorkflowSegmentResponse.decode(value),
  },
  /** Check the liveness of a worker via a simple heartbeat */
  heartbeat: {
    path: "/Worker/Heartbeat" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HeartbeatRequest): Buffer => Buffer.from(HeartbeatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HeartbeatRequest => HeartbeatRequest.decode(value),
    responseSerialize: (value: HeartbeatResponse): Buffer => Buffer.from(HeartbeatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HeartbeatResponse => HeartbeatResponse.decode(value),
  },
} as const;

export interface WorkerServer extends UntypedServiceImplementation {
  /** Execute a data function call */
  executeDataFunction: handleUnaryCall<ExecuteDataFunctionRequest, ExecuteDataFunctionResponse>;
  /** Execute a workflow segment (potentially all of it) */
  executeWorkflowSegment: handleUnaryCall<ExecuteWorkflowSegmentRequest, ExecuteWorkflowSegmentResponse>;
  /** Check the liveness of a worker via a simple heartbeat */
  heartbeat: handleUnaryCall<HeartbeatRequest, HeartbeatResponse>;
}

export interface WorkerClient extends Client {
  /** Execute a data function call */
  executeDataFunction(
    request: ExecuteDataFunctionRequest,
    callback: (error: ServiceError | null, response: ExecuteDataFunctionResponse) => void,
  ): ClientUnaryCall;
  executeDataFunction(
    request: ExecuteDataFunctionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExecuteDataFunctionResponse) => void,
  ): ClientUnaryCall;
  executeDataFunction(
    request: ExecuteDataFunctionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExecuteDataFunctionResponse) => void,
  ): ClientUnaryCall;
  /** Execute a workflow segment (potentially all of it) */
  executeWorkflowSegment(
    request: ExecuteWorkflowSegmentRequest,
    callback: (error: ServiceError | null, response: ExecuteWorkflowSegmentResponse) => void,
  ): ClientUnaryCall;
  executeWorkflowSegment(
    request: ExecuteWorkflowSegmentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExecuteWorkflowSegmentResponse) => void,
  ): ClientUnaryCall;
  executeWorkflowSegment(
    request: ExecuteWorkflowSegmentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExecuteWorkflowSegmentResponse) => void,
  ): ClientUnaryCall;
  /** Check the liveness of a worker via a simple heartbeat */
  heartbeat(
    request: HeartbeatRequest,
    callback: (error: ServiceError | null, response: HeartbeatResponse) => void,
  ): ClientUnaryCall;
  heartbeat(
    request: HeartbeatRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HeartbeatResponse) => void,
  ): ClientUnaryCall;
  heartbeat(
    request: HeartbeatRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HeartbeatResponse) => void,
  ): ClientUnaryCall;
}

export const WorkerClient = makeGenericClientConstructor(WorkerService, "Worker") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): WorkerClient;
  service: typeof WorkerService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
